import { VocabularyWord } from "@/types/flashcard";

export const BUSINESS_VOCABULARY: VocabularyWord[] = [
    {
        id: "biz_001",
        word: "entrepreneur",
        meaning: "doanh nhân, nhà khởi nghiệp",
        pronunciation: "/ˌɒntrəprəˈnɜːr/",
        partOfSpeech: "noun",
        example: "The entrepreneur founded three successful companies.",
        exampleTranslation: "Doanh nhân đã thành lập ba công ty thành công.",
        synonyms: [
            { word: "businessperson", level: "basic", meaning: "người kinh doanh" },
            { word: "founder", level: "intermediate", meaning: "người sáng lập" },
            { word: "tycoon", level: "advanced", meaning: "ông trùm" },
            { word: "mogul", level: "advanced", meaning: "đại gia" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_002",
        word: "revenue",
        meaning: "doanh thu",
        pronunciation: "/ˈrevənjuː/",
        partOfSpeech: "noun",
        example: "The company's revenue increased by 20% this year.",
        exampleTranslation: "Doanh thu công ty tăng 20% năm nay.",
        synonyms: [
            { word: "income", level: "basic", meaning: "thu nhập" },
            { word: "earnings", level: "intermediate", meaning: "thu nhập" },
            { word: "proceeds", level: "advanced", meaning: "tiền thu được" },
            { word: "turnover", level: "advanced", meaning: "doanh số" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_003",
        word: "profit",
        meaning: "lợi nhuận",
        pronunciation: "/ˈprɒfɪt/",
        partOfSpeech: "noun",
        example: "The company made a significant profit last quarter.",
        exampleTranslation: "Công ty đã có lợi nhuận đáng kể quý vừa qua.",
        synonyms: [
            { word: "gain", level: "basic", meaning: "lợi ích" },
            { word: "return", level: "intermediate", meaning: "lợi nhuận" },
            { word: "surplus", level: "advanced", meaning: "thặng dư" },
            { word: "yield", level: "advanced", meaning: "lợi tức" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_004",
        word: "negotiate",
        meaning: "đàm phán, thương lượng",
        pronunciation: "/nɪˈɡoʊʃieɪt/",
        partOfSpeech: "verb",
        example: "They negotiated a better deal with suppliers.",
        exampleTranslation: "Họ đã đàm phán một thỏa thuận tốt hơn với nhà cung cấp.",
        synonyms: [
            { word: "discuss", level: "basic", meaning: "thảo luận" },
            { word: "bargain", level: "intermediate", meaning: "mặc cả" },
            { word: "mediate", level: "advanced", meaning: "hòa giải" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_005",
        word: "investment",
        meaning: "đầu tư",
        pronunciation: "/ɪnˈvestmənt/",
        partOfSpeech: "noun",
        example: "Real estate is a popular investment choice.",
        exampleTranslation: "Bất động sản là lựa chọn đầu tư phổ biến.",
        synonyms: [
            { word: "funding", level: "intermediate", meaning: "nguồn vốn" },
            { word: "capital", level: "intermediate", meaning: "vốn" },
            { word: "venture", level: "advanced", meaning: "liên doanh" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_006",
        word: "strategy",
        meaning: "chiến lược",
        pronunciation: "/ˈstrætədʒi/",
        partOfSpeech: "noun",
        example: "The company developed a new marketing strategy.",
        exampleTranslation: "Công ty phát triển chiến lược marketing mới.",
        synonyms: [
            { word: "plan", level: "basic", meaning: "kế hoạch" },
            { word: "approach", level: "intermediate", meaning: "cách tiếp cận" },
            { word: "methodology", level: "advanced", meaning: "phương pháp luận" },
            { word: "blueprint", level: "advanced", meaning: "kế hoạch chi tiết" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_007",
        word: "stakeholder",
        meaning: "bên liên quan",
        pronunciation: "/ˈsteɪkhoʊldər/",
        partOfSpeech: "noun",
        example: "All stakeholders were consulted before the decision.",
        exampleTranslation: "Tất cả các bên liên quan đã được tham vấn trước quyết định.",
        synonyms: [
            { word: "investor", level: "intermediate", meaning: "nhà đầu tư" },
            { word: "shareholder", level: "intermediate", meaning: "cổ đông" },
            { word: "interested party", level: "advanced" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_008",
        word: "deadline",
        meaning: "thời hạn, hạn chót",
        pronunciation: "/ˈdedlaɪn/",
        partOfSpeech: "noun",
        example: "We must meet the project deadline.",
        exampleTranslation: "Chúng ta phải hoàn thành đúng thời hạn dự án.",
        synonyms: [
            { word: "due date", level: "basic" },
            { word: "time limit", level: "basic" },
            { word: "cutoff", level: "intermediate", meaning: "giới hạn" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_009",
        word: "competition",
        meaning: "sự cạnh tranh",
        pronunciation: "/ˌkɒmpəˈtɪʃn/",
        partOfSpeech: "noun",
        example: "Competition in the market is intense.",
        exampleTranslation: "Cạnh tranh trên thị trường rất gay gắt.",
        synonyms: [
            { word: "rivalry", level: "intermediate", meaning: "sự cạnh tranh" },
            { word: "contest", level: "intermediate", meaning: "cuộc thi" },
            { word: "contention", level: "advanced", meaning: "sự tranh chấp" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_010",
        word: "contract",
        meaning: "hợp đồng",
        pronunciation: "/ˈkɒntrækt/",
        partOfSpeech: "noun",
        example: "They signed a three-year contract.",
        exampleTranslation: "Họ ký hợp đồng ba năm.",
        synonyms: [
            { word: "agreement", level: "basic", meaning: "thỏa thuận" },
            { word: "deal", level: "basic", meaning: "thỏa thuận" },
            { word: "accord", level: "advanced", meaning: "hiệp định" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_011",
        word: "productivity",
        meaning: "năng suất",
        pronunciation: "/ˌprɒdʌkˈtɪvəti/",
        partOfSpeech: "noun",
        example: "New tools have increased productivity.",
        exampleTranslation: "Công cụ mới đã tăng năng suất.",
        synonyms: [
            { word: "efficiency", level: "intermediate", meaning: "hiệu quả" },
            { word: "output", level: "intermediate", meaning: "sản lượng" },
            { word: "performance", level: "intermediate", meaning: "hiệu suất" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_012",
        word: "budget",
        meaning: "ngân sách",
        pronunciation: "/ˈbʌdʒɪt/",
        partOfSpeech: "noun",
        example: "The project exceeded its budget.",
        exampleTranslation: "Dự án đã vượt ngân sách.",
        synonyms: [
            { word: "funds", level: "basic", meaning: "quỹ" },
            { word: "allocation", level: "advanced", meaning: "phân bổ" },
            { word: "financial plan", level: "intermediate" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_013",
        word: "marketing",
        meaning: "tiếp thị, marketing",
        pronunciation: "/ˈmɑːrkɪtɪŋ/",
        partOfSpeech: "noun",
        example: "Digital marketing is essential for modern businesses.",
        exampleTranslation: "Tiếp thị số là thiết yếu cho doanh nghiệp hiện đại.",
        synonyms: [
            { word: "advertising", level: "basic", meaning: "quảng cáo" },
            { word: "promotion", level: "intermediate", meaning: "quảng bá" },
            { word: "branding", level: "advanced", meaning: "xây dựng thương hiệu" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_014",
        word: "merger",
        meaning: "sáp nhập",
        pronunciation: "/ˈmɜːrdʒər/",
        partOfSpeech: "noun",
        example: "The merger created the largest company in the industry.",
        exampleTranslation: "Việc sáp nhập đã tạo ra công ty lớn nhất trong ngành.",
        synonyms: [
            { word: "combination", level: "basic", meaning: "sự kết hợp" },
            { word: "union", level: "intermediate", meaning: "liên minh" },
            { word: "consolidation", level: "advanced", meaning: "hợp nhất" },
            { word: "amalgamation", level: "academic", meaning: "sáp nhập" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_015",
        word: "acquisition",
        meaning: "sự mua lại, thâu tóm",
        pronunciation: "/ˌækwɪˈzɪʃn/",
        partOfSpeech: "noun",
        example: "The acquisition was worth $5 billion.",
        exampleTranslation: "Thương vụ mua lại trị giá 5 tỷ đô la.",
        synonyms: [
            { word: "purchase", level: "basic", meaning: "mua" },
            { word: "takeover", level: "intermediate", meaning: "tiếp quản" },
            { word: "procurement", level: "advanced", meaning: "thu mua" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_016",
        word: "outsource",
        meaning: "thuê ngoài",
        pronunciation: "/ˈaʊtsɔːrs/",
        partOfSpeech: "verb",
        example: "Many companies outsource IT services.",
        exampleTranslation: "Nhiều công ty thuê ngoài dịch vụ IT.",
        synonyms: [
            { word: "contract out", level: "intermediate" },
            { word: "delegate", level: "intermediate", meaning: "ủy thác" },
            { word: "subcontract", level: "advanced", meaning: "thầu phụ" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_017",
        word: "workforce",
        meaning: "lực lượng lao động",
        pronunciation: "/ˈwɜːrkfɔːrs/",
        partOfSpeech: "noun",
        example: "The company has a diverse workforce.",
        exampleTranslation: "Công ty có lực lượng lao động đa dạng.",
        synonyms: [
            { word: "employees", level: "basic", meaning: "nhân viên" },
            { word: "staff", level: "basic", meaning: "nhân viên" },
            { word: "personnel", level: "intermediate", meaning: "nhân sự" },
            { word: "labor force", level: "intermediate" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_018",
        word: "client",
        meaning: "khách hàng",
        pronunciation: "/ˈklaɪənt/",
        partOfSpeech: "noun",
        example: "We value our long-term clients.",
        exampleTranslation: "Chúng tôi trân trọng khách hàng lâu năm.",
        synonyms: [
            { word: "customer", level: "basic", meaning: "khách hàng" },
            { word: "patron", level: "advanced", meaning: "khách quen" },
            { word: "buyer", level: "basic", meaning: "người mua" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_019",
        word: "innovative",
        meaning: "sáng tạo, đổi mới",
        pronunciation: "/ˈɪnəvətɪv/",
        partOfSpeech: "adjective",
        example: "They developed an innovative business model.",
        exampleTranslation: "Họ phát triển mô hình kinh doanh sáng tạo.",
        synonyms: [
            { word: "creative", level: "basic", meaning: "sáng tạo" },
            { word: "original", level: "intermediate", meaning: "độc đáo" },
            { word: "groundbreaking", level: "advanced", meaning: "đột phá" },
            { word: "pioneering", level: "academic", meaning: "tiên phong" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_020",
        word: "liability",
        meaning: "trách nhiệm pháp lý, nợ phải trả",
        pronunciation: "/ˌlaɪəˈbɪləti/",
        partOfSpeech: "noun",
        example: "The company has significant liabilities.",
        exampleTranslation: "Công ty có các khoản nợ phải trả đáng kể.",
        synonyms: [
            { word: "debt", level: "basic", meaning: "nợ" },
            { word: "obligation", level: "intermediate", meaning: "nghĩa vụ" },
            { word: "responsibility", level: "intermediate", meaning: "trách nhiệm" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_021",
        word: "asset",
        meaning: "tài sản",
        pronunciation: "/ˈæset/",
        partOfSpeech: "noun",
        example: "Real estate is a valuable asset.",
        exampleTranslation: "Bất động sản là tài sản có giá trị.",
        synonyms: [
            { word: "property", level: "basic", meaning: "tài sản" },
            { word: "resource", level: "intermediate", meaning: "nguồn lực" },
            { word: "holding", level: "advanced", meaning: "sở hữu" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_022",
        word: "entrepreneur",
        meaning: "doanh nhân, chủ doanh nghiệp",
        pronunciation: "/ˌɒntrəprəˈnɜːr/",
        partOfSpeech: "noun",
        example: "Successful entrepreneurs take calculated risks.",
        exampleTranslation: "Doanh nhân thành công biết tính toán rủi ro.",
        synonyms: [
            { word: "businessperson", level: "basic" },
            { word: "founder", level: "intermediate", meaning: "người sáng lập" },
            { word: "enterprise owner", level: "advanced" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_023",
        word: "implement",
        meaning: "thực hiện, triển khai",
        pronunciation: "/ˈɪmplɪment/",
        partOfSpeech: "verb",
        example: "We will implement the new policy next month.",
        exampleTranslation: "Chúng tôi sẽ triển khai chính sách mới vào tháng tới.",
        synonyms: [
            { word: "execute", level: "intermediate", meaning: "thực thi" },
            { word: "carry out", level: "basic" },
            { word: "enact", level: "advanced", meaning: "ban hành" },
            { word: "effectuate", level: "academic", meaning: "thực hiện" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_024",
        word: "benchmark",
        meaning: "tiêu chuẩn, điểm chuẩn",
        pronunciation: "/ˈbentʃmɑːrk/",
        partOfSpeech: "noun",
        example: "This company sets the benchmark for quality.",
        exampleTranslation: "Công ty này đặt chuẩn mực về chất lượng.",
        synonyms: [
            { word: "standard", level: "basic", meaning: "tiêu chuẩn" },
            { word: "reference point", level: "intermediate" },
            { word: "yardstick", level: "advanced", meaning: "thước đo" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_025",
        word: "franchise",
        meaning: "nhượng quyền thương mại",
        pronunciation: "/ˈfræntʃaɪz/",
        partOfSpeech: "noun",
        example: "McDonald's is one of the largest franchises.",
        exampleTranslation: "McDonald's là một trong những hệ thống nhượng quyền lớn nhất.",
        synonyms: [
            { word: "license", level: "intermediate", meaning: "giấy phép" },
            { word: "dealership", level: "intermediate", meaning: "đại lý" },
            { word: "concession", level: "advanced", meaning: "nhượng quyền" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_026",
        word: "sustainable",
        meaning: "bền vững",
        pronunciation: "/səˈsteɪnəbl/",
        partOfSpeech: "adjective",
        example: "We aim for sustainable business growth.",
        exampleTranslation: "Chúng tôi hướng tới tăng trưởng kinh doanh bền vững.",
        synonyms: [
            { word: "lasting", level: "basic", meaning: "lâu dài" },
            { word: "viable", level: "advanced", meaning: "khả thi" },
            { word: "enduring", level: "advanced", meaning: "bền bỉ" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_027",
        word: "collaborate",
        meaning: "cộng tác, hợp tác",
        pronunciation: "/kəˈlæbəreɪt/",
        partOfSpeech: "verb",
        example: "The two companies decided to collaborate.",
        exampleTranslation: "Hai công ty quyết định hợp tác.",
        synonyms: [
            { word: "cooperate", level: "basic", meaning: "hợp tác" },
            { word: "partner", level: "intermediate", meaning: "đối tác" },
            { word: "team up", level: "basic" },
            { word: "join forces", level: "intermediate" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_028",
        word: "recession",
        meaning: "suy thoái kinh tế",
        pronunciation: "/rɪˈseʃn/",
        partOfSpeech: "noun",
        example: "The recession affected many businesses.",
        exampleTranslation: "Suy thoái kinh tế ảnh hưởng nhiều doanh nghiệp.",
        synonyms: [
            { word: "downturn", level: "intermediate", meaning: "suy giảm" },
            { word: "slump", level: "intermediate", meaning: "sụt giảm" },
            { word: "depression", level: "advanced", meaning: "khủng hoảng" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_029",
        word: "retail",
        meaning: "bán lẻ",
        pronunciation: "/ˈriːteɪl/",
        partOfSpeech: "noun",
        example: "The retail industry is evolving rapidly.",
        exampleTranslation: "Ngành bán lẻ đang phát triển nhanh chóng.",
        synonyms: [
            { word: "sales", level: "basic", meaning: "bán hàng" },
            { word: "merchandising", level: "advanced", meaning: "bán hàng hóa" },
            { word: "trade", level: "intermediate", meaning: "thương mại" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_030",
        word: "wholesale",
        meaning: "bán sỉ, bán buôn",
        pronunciation: "/ˈhoʊlseɪl/",
        partOfSpeech: "noun",
        example: "They buy products at wholesale prices.",
        exampleTranslation: "Họ mua sản phẩm với giá sỉ.",
        synonyms: [
            { word: "bulk sale", level: "intermediate" },
            { word: "trade sale", level: "advanced" },
            { word: "distribution", level: "intermediate", meaning: "phân phối" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_031",
        word: "inventory",
        meaning: "hàng tồn kho",
        pronunciation: "/ˈɪnvəntɔːri/",
        partOfSpeech: "noun",
        example: "We need to reduce our inventory.",
        exampleTranslation: "Chúng tôi cần giảm hàng tồn kho.",
        synonyms: [
            { word: "stock", level: "basic", meaning: "kho hàng" },
            { word: "supplies", level: "intermediate", meaning: "vật tư" },
            { word: "merchandise", level: "intermediate", meaning: "hàng hóa" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_032",
        word: "negotiate",
        meaning: "thương lượng, đàm phán",
        pronunciation: "/nɪˈɡoʊʃieɪt/",
        partOfSpeech: "verb",
        example: "She negotiated a higher salary.",
        exampleTranslation: "Cô ấy đã thương lượng mức lương cao hơn.",
        synonyms: [
            { word: "bargain", level: "intermediate", meaning: "mặc cả" },
            { word: "discuss terms", level: "intermediate" },
            { word: "broker", level: "advanced", meaning: "môi giới" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_033",
        word: "launch",
        meaning: "ra mắt, tung ra",
        pronunciation: "/lɔːntʃ/",
        partOfSpeech: "verb",
        example: "The company will launch a new product next week.",
        exampleTranslation: "Công ty sẽ ra mắt sản phẩm mới vào tuần tới.",
        synonyms: [
            { word: "introduce", level: "basic", meaning: "giới thiệu" },
            { word: "release", level: "intermediate", meaning: "phát hành" },
            { word: "unveil", level: "advanced", meaning: "công bố" },
            { word: "inaugurate", level: "academic", meaning: "khai trương" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_034",
        word: "trademark",
        meaning: "nhãn hiệu",
        pronunciation: "/ˈtreɪdmɑːrk/",
        partOfSpeech: "noun",
        example: "The logo is a registered trademark.",
        exampleTranslation: "Logo là nhãn hiệu đã đăng ký.",
        synonyms: [
            { word: "brand", level: "basic", meaning: "thương hiệu" },
            { word: "logo", level: "basic" },
            { word: "registered mark", level: "advanced" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_035",
        word: "dividend",
        meaning: "cổ tức",
        pronunciation: "/ˈdɪvɪdend/",
        partOfSpeech: "noun",
        example: "Shareholders received a dividend payment.",
        exampleTranslation: "Cổ đông nhận được khoản thanh toán cổ tức.",
        synonyms: [
            { word: "share", level: "intermediate", meaning: "phần chia" },
            { word: "payout", level: "intermediate", meaning: "chi trả" },
            { word: "distribution", level: "advanced", meaning: "phân phối" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_036",
        word: "entrepreneur",
        meaning: "doanh nhân",
        pronunciation: "/ˌɒntrəprəˈnɜːr/",
        partOfSpeech: "noun",
        example: "She is a successful entrepreneur.",
        exampleTranslation: "Cô ấy là một doanh nhân thành đạt.",
        synonyms: [
            { word: "business owner", level: "basic" },
            { word: "founder", level: "intermediate", meaning: "người sáng lập" },
            { word: "industrialist", level: "advanced", meaning: "nhà công nghiệp" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_037",
        word: "deadline",
        meaning: "hạn chót",
        pronunciation: "/ˈdedlaɪn/",
        partOfSpeech: "noun",
        example: "We must meet the deadline.",
        exampleTranslation: "Chúng ta phải hoàn thành trước hạn chót.",
        synonyms: [
            { word: "due date", level: "basic" },
            { word: "time limit", level: "basic" },
            { word: "cutoff date", level: "intermediate" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_038",
        word: "expense",
        meaning: "chi phí",
        pronunciation: "/ɪkˈspens/",
        partOfSpeech: "noun",
        example: "Travel expenses will be reimbursed.",
        exampleTranslation: "Chi phí đi lại sẽ được hoàn trả.",
        synonyms: [
            { word: "cost", level: "basic", meaning: "chi phí" },
            { word: "expenditure", level: "advanced", meaning: "chi tiêu" },
            { word: "outlay", level: "advanced", meaning: "khoản chi" },
        ],
        topic: "business",
        difficulty: "beginner",
    },
    {
        id: "biz_039",
        word: "executive",
        meaning: "giám đốc điều hành",
        pronunciation: "/ɪɡˈzekjətɪv/",
        partOfSpeech: "noun",
        example: "The executive made the final decision.",
        exampleTranslation: "Giám đốc điều hành đã đưa ra quyết định cuối cùng.",
        synonyms: [
            { word: "manager", level: "basic", meaning: "quản lý" },
            { word: "director", level: "intermediate", meaning: "giám đốc" },
            { word: "administrator", level: "advanced", meaning: "người điều hành" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_040",
        word: "optimize",
        meaning: "tối ưu hóa",
        pronunciation: "/ˈɒptɪmaɪz/",
        partOfSpeech: "verb",
        example: "We need to optimize our processes.",
        exampleTranslation: "Chúng ta cần tối ưu hóa quy trình.",
        synonyms: [
            { word: "improve", level: "basic", meaning: "cải thiện" },
            { word: "enhance", level: "intermediate", meaning: "nâng cao" },
            { word: "streamline", level: "advanced", meaning: "tinh gọn" },
            { word: "maximize", level: "intermediate", meaning: "tối đa hóa" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_041",
        word: "forecast",
        meaning: "dự báo",
        pronunciation: "/ˈfɔːrkæst/",
        partOfSpeech: "noun",
        example: "The sales forecast looks promising.",
        exampleTranslation: "Dự báo doanh số có vẻ khả quan.",
        synonyms: [
            { word: "prediction", level: "basic", meaning: "dự đoán" },
            { word: "projection", level: "intermediate", meaning: "dự kiến" },
            { word: "prognosis", level: "academic", meaning: "tiên lượng" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_042",
        word: "quarterly",
        meaning: "hàng quý",
        pronunciation: "/ˈkwɔːrtərli/",
        partOfSpeech: "adjective",
        example: "We have quarterly financial reports.",
        exampleTranslation: "Chúng tôi có báo cáo tài chính hàng quý.",
        synonyms: [
            { word: "every three months", level: "basic" },
            { word: "periodic", level: "intermediate", meaning: "định kỳ" },
            { word: "trimestral", level: "academic" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_043",
        word: "leverage",
        meaning: "đòn bẩy, tận dụng",
        pronunciation: "/ˈlevərɪdʒ/",
        partOfSpeech: "verb",
        example: "We should leverage our strengths.",
        exampleTranslation: "Chúng ta nên tận dụng thế mạnh của mình.",
        synonyms: [
            { word: "use", level: "basic", meaning: "sử dụng" },
            { word: "utilize", level: "intermediate", meaning: "tận dụng" },
            { word: "exploit", level: "advanced", meaning: "khai thác" },
            { word: "capitalize on", level: "advanced" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_044",
        word: "diversify",
        meaning: "đa dạng hóa",
        pronunciation: "/daɪˈvɜːrsɪfaɪ/",
        partOfSpeech: "verb",
        example: "It's wise to diversify your investments.",
        exampleTranslation: "Khôn ngoan nếu đa dạng hóa đầu tư.",
        synonyms: [
            { word: "vary", level: "basic", meaning: "thay đổi" },
            { word: "expand", level: "intermediate", meaning: "mở rộng" },
            { word: "branch out", level: "intermediate" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_045",
        word: "infrastructure",
        meaning: "cơ sở hạ tầng",
        pronunciation: "/ˈɪnfrəstrʌktʃər/",
        partOfSpeech: "noun",
        example: "The company invested in IT infrastructure.",
        exampleTranslation: "Công ty đầu tư vào cơ sở hạ tầng IT.",
        synonyms: [
            { word: "foundation", level: "intermediate", meaning: "nền tảng" },
            { word: "framework", level: "intermediate", meaning: "khung" },
            { word: "base", level: "basic", meaning: "nền" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_046",
        word: "scalable",
        meaning: "có khả năng mở rộng",
        pronunciation: "/ˈskeɪləbl/",
        partOfSpeech: "adjective",
        example: "We need a scalable business model.",
        exampleTranslation: "Chúng tôi cần mô hình kinh doanh có khả năng mở rộng.",
        synonyms: [
            { word: "expandable", level: "basic", meaning: "có thể mở rộng" },
            { word: "adaptable", level: "intermediate", meaning: "thích nghi" },
            { word: "flexible", level: "intermediate", meaning: "linh hoạt" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_047",
        word: "lucrative",
        meaning: "sinh lời, có lãi",
        pronunciation: "/ˈluːkrətɪv/",
        partOfSpeech: "adjective",
        example: "It was a lucrative business opportunity.",
        exampleTranslation: "Đó là cơ hội kinh doanh sinh lời.",
        synonyms: [
            { word: "profitable", level: "basic", meaning: "có lợi nhuận" },
            { word: "rewarding", level: "intermediate", meaning: "đáng giá" },
            { word: "remunerative", level: "academic", meaning: "có thu nhập" },
        ],
        topic: "business",
        difficulty: "advanced",
    },
    {
        id: "biz_048",
        word: "entrepreneur",
        meaning: "doanh nhân khởi nghiệp",
        pronunciation: "/ˌɒntrəprəˈnɜːr/",
        partOfSpeech: "noun",
        example: "Every entrepreneur faces challenges.",
        exampleTranslation: "Mọi doanh nhân đều đối mặt với thử thách.",
        synonyms: [
            { word: "business starter", level: "basic" },
            { word: "innovator", level: "intermediate", meaning: "người đổi mới" },
            { word: "venture capitalist", level: "advanced" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_049",
        word: "recession",
        meaning: "suy thoái",
        pronunciation: "/rɪˈseʃn/",
        partOfSpeech: "noun",
        example: "The economy is heading into a recession.",
        exampleTranslation: "Nền kinh tế đang hướng tới suy thoái.",
        synonyms: [
            { word: "downturn", level: "intermediate", meaning: "sự sụt giảm" },
            { word: "decline", level: "intermediate", meaning: "sự suy giảm" },
            { word: "slump", level: "advanced", meaning: "sự sụp đổ" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
    {
        id: "biz_050",
        word: "streamline",
        meaning: "tinh gọn, hợp lý hóa",
        pronunciation: "/ˈstriːmlaɪn/",
        partOfSpeech: "verb",
        example: "We need to streamline our operations.",
        exampleTranslation: "Chúng tôi cần tinh gọn hoạt động.",
        synonyms: [
            { word: "simplify", level: "basic", meaning: "đơn giản hóa" },
            { word: "optimize", level: "intermediate", meaning: "tối ưu hóa" },
            { word: "rationalize", level: "advanced", meaning: "hợp lý hóa" },
        ],
        topic: "business",
        difficulty: "intermediate",
    },
];
