import { VocabularyWord } from "@/types/flashcard";

export const EDUCATION_VOCABULARY: VocabularyWord[] = [
    {
        id: "edu_001",
        word: "academic",
        meaning: "học thuật, thuộc về giáo dục",
        pronunciation: "/ˌækəˈdemɪk/",
        partOfSpeech: "adjective",
        example: "She has an impressive academic record.",
        exampleTranslation: "Cô ấy có thành tích học tập ấn tượng.",
        synonyms: [
            { word: "scholarly", level: "advanced", meaning: "học thuật" },
            { word: "educational", level: "basic", meaning: "giáo dục" },
            { word: "intellectual", level: "advanced", meaning: "trí tuệ" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_002",
        word: "curriculum",
        meaning: "chương trình giảng dạy",
        pronunciation: "/kəˈrɪkjələm/",
        partOfSpeech: "noun",
        example: "The school updated its curriculum this year.",
        exampleTranslation: "Trường đã cập nhật chương trình giảng dạy năm nay.",
        synonyms: [
            { word: "syllabus", level: "intermediate", meaning: "đề cương" },
            { word: "course of study", level: "intermediate" },
            { word: "educational program", level: "basic" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_003",
        word: "graduate",
        meaning: "tốt nghiệp",
        pronunciation: "/ˈɡrædʒueɪt/",
        partOfSpeech: "verb",
        example: "She will graduate from university next year.",
        exampleTranslation: "Cô ấy sẽ tốt nghiệp đại học vào năm tới.",
        synonyms: [
            { word: "complete", level: "basic", meaning: "hoàn thành" },
            { word: "finish", level: "basic", meaning: "kết thúc" },
            { word: "qualify", level: "advanced", meaning: "đủ điều kiện" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_004",
        word: "scholarship",
        meaning: "học bổng",
        pronunciation: "/ˈskɒlərʃɪp/",
        partOfSpeech: "noun",
        example: "He received a full scholarship to Harvard.",
        exampleTranslation: "Anh ấy nhận được học bổng toàn phần vào Harvard.",
        synonyms: [
            { word: "grant", level: "intermediate", meaning: "trợ cấp" },
            { word: "fellowship", level: "advanced", meaning: "học bổng nghiên cứu" },
            { word: "bursary", level: "advanced", meaning: "học bổng hỗ trợ" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_005",
        word: "evaluate",
        meaning: "đánh giá",
        pronunciation: "/ɪˈvæljueɪt/",
        partOfSpeech: "verb",
        example: "Teachers evaluate students' progress regularly.",
        exampleTranslation: "Giáo viên đánh giá tiến bộ của học sinh thường xuyên.",
        synonyms: [
            { word: "assess", level: "intermediate", meaning: "đánh giá" },
            { word: "judge", level: "basic", meaning: "phán xét" },
            { word: "appraise", level: "advanced", meaning: "thẩm định" },
            { word: "scrutinize", level: "academic", meaning: "xem xét kỹ" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_006",
        word: "comprehend",
        meaning: "hiểu, lĩnh hội",
        pronunciation: "/ˌkɒmprɪˈhend/",
        partOfSpeech: "verb",
        example: "It takes time to fully comprehend complex theories.",
        exampleTranslation: "Cần thời gian để hiểu đầy đủ các lý thuyết phức tạp.",
        synonyms: [
            { word: "understand", level: "basic", meaning: "hiểu" },
            { word: "grasp", level: "intermediate", meaning: "nắm bắt" },
            { word: "apprehend", level: "academic", meaning: "lĩnh hội" },
            { word: "fathom", level: "advanced", meaning: "thấu hiểu" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_007",
        word: "thesis",
        meaning: "luận văn, luận điểm",
        pronunciation: "/ˈθiːsɪs/",
        partOfSpeech: "noun",
        example: "She is working on her Master's thesis.",
        exampleTranslation: "Cô ấy đang làm luận văn Thạc sĩ.",
        synonyms: [
            { word: "dissertation", level: "advanced", meaning: "luận án" },
            { word: "paper", level: "basic", meaning: "bài nghiên cứu" },
            { word: "treatise", level: "academic", meaning: "chuyên luận" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_008",
        word: "research",
        meaning: "nghiên cứu",
        pronunciation: "/rɪˈsɜːrtʃ/",
        partOfSpeech: "noun",
        example: "The research findings were published in a journal.",
        exampleTranslation: "Kết quả nghiên cứu đã được công bố trên tạp chí.",
        synonyms: [
            { word: "study", level: "basic", meaning: "nghiên cứu" },
            { word: "investigation", level: "intermediate", meaning: "điều tra" },
            { word: "inquiry", level: "advanced", meaning: "khảo cứu" },
            { word: "exploration", level: "intermediate", meaning: "khám phá" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_009",
        word: "lecture",
        meaning: "bài giảng",
        pronunciation: "/ˈlektʃər/",
        partOfSpeech: "noun",
        example: "The professor gave an interesting lecture on history.",
        exampleTranslation: "Giáo sư đã có bài giảng thú vị về lịch sử.",
        synonyms: [
            { word: "talk", level: "basic", meaning: "bài nói" },
            { word: "presentation", level: "intermediate", meaning: "bài trình bày" },
            { word: "discourse", level: "academic", meaning: "diễn thuyết" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_010",
        word: "tuition",
        meaning: "học phí",
        pronunciation: "/tjuːˈɪʃn/",
        partOfSpeech: "noun",
        example: "University tuition fees have increased.",
        exampleTranslation: "Học phí đại học đã tăng.",
        synonyms: [
            { word: "fees", level: "basic", meaning: "phí" },
            { word: "educational costs", level: "intermediate" },
            { word: "instruction charges", level: "advanced" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_011",
        word: "assignment",
        meaning: "bài tập, nhiệm vụ",
        pronunciation: "/əˈsaɪnmənt/",
        partOfSpeech: "noun",
        example: "The assignment is due next Monday.",
        exampleTranslation: "Bài tập phải nộp vào thứ Hai tuần tới.",
        synonyms: [
            { word: "task", level: "basic", meaning: "nhiệm vụ" },
            { word: "homework", level: "basic", meaning: "bài tập về nhà" },
            { word: "project", level: "intermediate", meaning: "dự án" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_012",
        word: "examination",
        meaning: "kỳ thi, bài kiểm tra",
        pronunciation: "/ɪɡˌzæmɪˈneɪʃn/",
        partOfSpeech: "noun",
        example: "The final examination will cover all chapters.",
        exampleTranslation: "Kỳ thi cuối kỳ sẽ bao gồm tất cả các chương.",
        synonyms: [
            { word: "test", level: "basic", meaning: "bài kiểm tra" },
            { word: "exam", level: "basic", meaning: "kỳ thi" },
            { word: "assessment", level: "intermediate", meaning: "đánh giá" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_013",
        word: "methodology",
        meaning: "phương pháp luận",
        pronunciation: "/ˌmeθəˈdɒlədʒi/",
        partOfSpeech: "noun",
        example: "The study used a qualitative methodology.",
        exampleTranslation: "Nghiên cứu sử dụng phương pháp luận định tính.",
        synonyms: [
            { word: "method", level: "basic", meaning: "phương pháp" },
            { word: "approach", level: "intermediate", meaning: "cách tiếp cận" },
            { word: "procedure", level: "intermediate", meaning: "quy trình" },
        ],
        topic: "education",
        difficulty: "advanced",
    },
    {
        id: "edu_014",
        word: "discipline",
        meaning: "kỷ luật, ngành học",
        pronunciation: "/ˈdɪsəplɪn/",
        partOfSpeech: "noun",
        example: "History is an important academic discipline.",
        exampleTranslation: "Lịch sử là một ngành học thuật quan trọng.",
        synonyms: [
            { word: "field", level: "basic", meaning: "lĩnh vực" },
            { word: "subject", level: "basic", meaning: "môn học" },
            { word: "branch of knowledge", level: "advanced" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_015",
        word: "certificate",
        meaning: "chứng chỉ, bằng cấp",
        pronunciation: "/sərˈtɪfɪkət/",
        partOfSpeech: "noun",
        example: "She received a certificate of completion.",
        exampleTranslation: "Cô ấy nhận được chứng chỉ hoàn thành.",
        synonyms: [
            { word: "diploma", level: "intermediate", meaning: "bằng cấp" },
            { word: "credential", level: "advanced", meaning: "chứng chỉ" },
            { word: "qualification", level: "intermediate", meaning: "bằng cấp" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_016",
        word: "enroll",
        meaning: "ghi danh, đăng ký",
        pronunciation: "/ɪnˈroʊl/",
        partOfSpeech: "verb",
        example: "Students must enroll before the deadline.",
        exampleTranslation: "Sinh viên phải ghi danh trước hạn chót.",
        synonyms: [
            { word: "register", level: "basic", meaning: "đăng ký" },
            { word: "sign up", level: "basic", meaning: "đăng ký" },
            { word: "matriculate", level: "academic", meaning: "nhập học" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_017",
        word: "semester",
        meaning: "học kỳ",
        pronunciation: "/sɪˈmestər/",
        partOfSpeech: "noun",
        example: "The course runs for one semester.",
        exampleTranslation: "Khóa học kéo dài một học kỳ.",
        synonyms: [
            { word: "term", level: "basic", meaning: "học kỳ" },
            { word: "academic period", level: "intermediate" },
            { word: "session", level: "intermediate", meaning: "kỳ học" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_018",
        word: "undergraduate",
        meaning: "sinh viên đại học",
        pronunciation: "/ˌʌndərˈɡrædʒuət/",
        partOfSpeech: "noun",
        example: "She is an undergraduate studying biology.",
        exampleTranslation: "Cô ấy là sinh viên đại học học ngành sinh học.",
        synonyms: [
            { word: "college student", level: "basic" },
            { word: "university student", level: "basic" },
            { word: "undergrad", level: "basic" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_019",
        word: "postgraduate",
        meaning: "sau đại học",
        pronunciation: "/ˌpoʊstˈɡrædʒuət/",
        partOfSpeech: "noun",
        example: "He is pursuing postgraduate studies in law.",
        exampleTranslation: "Anh ấy đang theo học sau đại học ngành luật.",
        synonyms: [
            { word: "graduate student", level: "intermediate" },
            { word: "Master's student", level: "intermediate" },
            { word: "doctoral candidate", level: "advanced" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_020",
        word: "professor",
        meaning: "giáo sư",
        pronunciation: "/prəˈfesər/",
        partOfSpeech: "noun",
        example: "The professor is an expert in physics.",
        exampleTranslation: "Giáo sư là chuyên gia về vật lý.",
        synonyms: [
            { word: "teacher", level: "basic", meaning: "giáo viên" },
            { word: "lecturer", level: "intermediate", meaning: "giảng viên" },
            { word: "academic", level: "advanced", meaning: "học giả" },
            { word: "scholar", level: "advanced", meaning: "học giả" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_021",
        word: "literacy",
        meaning: "biết chữ, khả năng đọc viết",
        pronunciation: "/ˈlɪtərəsi/",
        partOfSpeech: "noun",
        example: "Literacy rates have improved significantly.",
        exampleTranslation: "Tỷ lệ biết chữ đã cải thiện đáng kể.",
        synonyms: [
            { word: "reading ability", level: "basic" },
            { word: "education level", level: "intermediate" },
            { word: "learnedness", level: "academic" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_022",
        word: "competence",
        meaning: "năng lực, khả năng",
        pronunciation: "/ˈkɒmpɪtəns/",
        partOfSpeech: "noun",
        example: "Language competence develops through practice.",
        exampleTranslation: "Năng lực ngôn ngữ phát triển qua thực hành.",
        synonyms: [
            { word: "ability", level: "basic", meaning: "khả năng" },
            { word: "skill", level: "basic", meaning: "kỹ năng" },
            { word: "proficiency", level: "advanced", meaning: "thành thạo" },
            { word: "expertise", level: "advanced", meaning: "chuyên môn" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_023",
        word: "compulsory",
        meaning: "bắt buộc",
        pronunciation: "/kəmˈpʌlsəri/",
        partOfSpeech: "adjective",
        example: "Education is compulsory until age 16.",
        exampleTranslation: "Giáo dục là bắt buộc đến 16 tuổi.",
        synonyms: [
            { word: "mandatory", level: "intermediate", meaning: "bắt buộc" },
            { word: "required", level: "basic", meaning: "yêu cầu" },
            { word: "obligatory", level: "advanced", meaning: "bắt buộc" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_024",
        word: "elective",
        meaning: "tự chọn",
        pronunciation: "/ɪˈlektɪv/",
        partOfSpeech: "adjective",
        example: "Students can choose from several elective courses.",
        exampleTranslation: "Sinh viên có thể chọn từ nhiều môn tự chọn.",
        synonyms: [
            { word: "optional", level: "basic", meaning: "tùy chọn" },
            { word: "voluntary", level: "intermediate", meaning: "tự nguyện" },
            { word: "discretionary", level: "advanced", meaning: "tùy ý" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_025",
        word: "analyze",
        meaning: "phân tích",
        pronunciation: "/ˈænəlaɪz/",
        partOfSpeech: "verb",
        example: "Students learn to analyze complex problems.",
        exampleTranslation: "Sinh viên học cách phân tích các vấn đề phức tạp.",
        synonyms: [
            { word: "examine", level: "basic", meaning: "kiểm tra" },
            { word: "study", level: "basic", meaning: "nghiên cứu" },
            { word: "dissect", level: "advanced", meaning: "mổ xẻ" },
            { word: "scrutinize", level: "academic", meaning: "xem xét kỹ" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_026",
        word: "plagiarism",
        meaning: "đạo văn",
        pronunciation: "/ˈpleɪdʒərɪzəm/",
        partOfSpeech: "noun",
        example: "Plagiarism is a serious academic offense.",
        exampleTranslation: "Đạo văn là vi phạm học thuật nghiêm trọng.",
        synonyms: [
            { word: "copying", level: "basic", meaning: "sao chép" },
            { word: "cheating", level: "basic", meaning: "gian lận" },
            { word: "intellectual theft", level: "advanced" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_027",
        word: "mentor",
        meaning: "người cố vấn, hướng dẫn",
        pronunciation: "/ˈmentɔːr/",
        partOfSpeech: "noun",
        example: "She found a mentor to guide her career.",
        exampleTranslation: "Cô ấy tìm được một người cố vấn để hướng dẫn sự nghiệp.",
        synonyms: [
            { word: "guide", level: "basic", meaning: "người hướng dẫn" },
            { word: "advisor", level: "intermediate", meaning: "cố vấn" },
            { word: "counselor", level: "intermediate", meaning: "tư vấn viên" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_028",
        word: "tutorial",
        meaning: "buổi hướng dẫn",
        pronunciation: "/tjuːˈtɔːriəl/",
        partOfSpeech: "noun",
        example: "The tutorial helped me understand the topic better.",
        exampleTranslation: "Buổi hướng dẫn giúp tôi hiểu chủ đề tốt hơn.",
        synonyms: [
            { word: "lesson", level: "basic", meaning: "bài học" },
            { word: "class", level: "basic", meaning: "lớp học" },
            { word: "instruction session", level: "intermediate" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_029",
        word: "degree",
        meaning: "bằng cấp, học vị",
        pronunciation: "/dɪˈɡriː/",
        partOfSpeech: "noun",
        example: "She has a degree in computer science.",
        exampleTranslation: "Cô ấy có bằng khoa học máy tính.",
        synonyms: [
            { word: "qualification", level: "intermediate", meaning: "bằng cấp" },
            { word: "diploma", level: "intermediate", meaning: "văn bằng" },
            { word: "credential", level: "advanced", meaning: "chứng chỉ" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_030",
        word: "acquire",
        meaning: "đạt được, tiếp thu",
        pronunciation: "/əˈkwaɪər/",
        partOfSpeech: "verb",
        example: "Students acquire knowledge through study.",
        exampleTranslation: "Sinh viên tiếp thu kiến thức qua học tập.",
        synonyms: [
            { word: "gain", level: "basic", meaning: "đạt được" },
            { word: "obtain", level: "intermediate", meaning: "có được" },
            { word: "attain", level: "advanced", meaning: "đạt được" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_031",
        word: "seminar",
        meaning: "hội thảo, seminar",
        pronunciation: "/ˈsemɪnɑːr/",
        partOfSpeech: "noun",
        example: "He attended a seminar on leadership.",
        exampleTranslation: "Anh ấy tham dự hội thảo về lãnh đạo.",
        synonyms: [
            { word: "workshop", level: "intermediate", meaning: "hội thảo thực hành" },
            { word: "conference", level: "intermediate", meaning: "hội nghị" },
            { word: "symposium", level: "academic", meaning: "hội nghị chuyên đề" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_032",
        word: "cognitive",
        meaning: "nhận thức",
        pronunciation: "/ˈkɒɡnətɪv/",
        partOfSpeech: "adjective",
        example: "Cognitive development is crucial in early childhood.",
        exampleTranslation: "Phát triển nhận thức rất quan trọng ở giai đoạn đầu đời.",
        synonyms: [
            { word: "mental", level: "basic", meaning: "tinh thần" },
            { word: "intellectual", level: "intermediate", meaning: "trí tuệ" },
            { word: "perceptual", level: "advanced", meaning: "nhận thức" },
        ],
        topic: "education",
        difficulty: "advanced",
    },
    {
        id: "edu_033",
        word: "institution",
        meaning: "tổ chức, cơ sở giáo dục",
        pronunciation: "/ˌɪnstɪˈtjuːʃn/",
        partOfSpeech: "noun",
        example: "Harvard is a prestigious educational institution.",
        exampleTranslation: "Harvard là một tổ chức giáo dục uy tín.",
        synonyms: [
            { word: "organization", level: "basic", meaning: "tổ chức" },
            { word: "establishment", level: "intermediate", meaning: "cơ sở" },
            { word: "academy", level: "advanced", meaning: "học viện" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_034",
        word: "hypothesis",
        meaning: "giả thuyết",
        pronunciation: "/haɪˈpɒθəsɪs/",
        partOfSpeech: "noun",
        example: "The research tested the hypothesis.",
        exampleTranslation: "Nghiên cứu đã kiểm tra giả thuyết.",
        synonyms: [
            { word: "theory", level: "basic", meaning: "lý thuyết" },
            { word: "assumption", level: "intermediate", meaning: "giả định" },
            { word: "proposition", level: "advanced", meaning: "mệnh đề" },
            { word: "conjecture", level: "academic", meaning: "phỏng đoán" },
        ],
        topic: "education",
        difficulty: "advanced",
    },
    {
        id: "edu_035",
        word: "summarize",
        meaning: "tóm tắt",
        pronunciation: "/ˈsʌməraɪz/",
        partOfSpeech: "verb",
        example: "Please summarize the main points of the article.",
        exampleTranslation: "Xin hãy tóm tắt các điểm chính của bài báo.",
        synonyms: [
            { word: "outline", level: "intermediate", meaning: "phác họa" },
            { word: "recap", level: "intermediate", meaning: "tóm tắt lại" },
            { word: "encapsulate", level: "advanced", meaning: "tóm gọn" },
            { word: "condense", level: "advanced", meaning: "cô đọng" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_036",
        word: "practical",
        meaning: "thực hành, thực tế",
        pronunciation: "/ˈpræktɪkl/",
        partOfSpeech: "adjective",
        example: "Students gain practical experience through internships.",
        exampleTranslation: "Sinh viên có được kinh nghiệm thực hành qua thực tập.",
        synonyms: [
            { word: "hands-on", level: "intermediate", meaning: "thực hành" },
            { word: "applied", level: "intermediate", meaning: "ứng dụng" },
            { word: "pragmatic", level: "advanced", meaning: "thực dụng" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_037",
        word: "theoretical",
        meaning: "lý thuyết",
        pronunciation: "/ˌθɪəˈretɪkl/",
        partOfSpeech: "adjective",
        example: "The course covers both theoretical and practical aspects.",
        exampleTranslation: "Khóa học bao gồm cả khía cạnh lý thuyết và thực hành.",
        synonyms: [
            { word: "abstract", level: "intermediate", meaning: "trừu tượng" },
            { word: "conceptual", level: "advanced", meaning: "khái niệm" },
            { word: "hypothetical", level: "advanced", meaning: "giả thuyết" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_038",
        word: "critical thinking",
        meaning: "tư duy phản biện",
        pronunciation: "/ˈkrɪtɪkl ˈθɪŋkɪŋ/",
        partOfSpeech: "noun",
        example: "Critical thinking is an essential skill.",
        exampleTranslation: "Tư duy phản biện là kỹ năng thiết yếu.",
        synonyms: [
            { word: "analytical thinking", level: "intermediate" },
            { word: "logical reasoning", level: "advanced" },
            { word: "problem-solving", level: "intermediate" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_039",
        word: "peer",
        meaning: "bạn đồng trang lứa",
        pronunciation: "/pɪr/",
        partOfSpeech: "noun",
        example: "Students learn from their peers.",
        exampleTranslation: "Sinh viên học hỏi từ bạn bè cùng trang lứa.",
        synonyms: [
            { word: "colleague", level: "intermediate", meaning: "đồng nghiệp" },
            { word: "classmate", level: "basic", meaning: "bạn cùng lớp" },
            { word: "contemporary", level: "advanced", meaning: "người cùng thời" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_040",
        word: "extracurricular",
        meaning: "ngoại khóa",
        pronunciation: "/ˌekstrəkəˈrɪkjələr/",
        partOfSpeech: "adjective",
        example: "She participates in many extracurricular activities.",
        exampleTranslation: "Cô ấy tham gia nhiều hoạt động ngoại khóa.",
        synonyms: [
            { word: "after-school", level: "basic" },
            { word: "non-academic", level: "intermediate" },
            { word: "supplementary", level: "advanced", meaning: "bổ sung" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_041",
        word: "revise",
        meaning: "ôn tập, sửa đổi",
        pronunciation: "/rɪˈvaɪz/",
        partOfSpeech: "verb",
        example: "Students should revise before exams.",
        exampleTranslation: "Sinh viên nên ôn tập trước kỳ thi.",
        synonyms: [
            { word: "review", level: "basic", meaning: "xem lại" },
            { word: "study", level: "basic", meaning: "học" },
            { word: "recapitulate", level: "academic", meaning: "tóm tắt lại" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_042",
        word: "collaborate",
        meaning: "hợp tác, cộng tác",
        pronunciation: "/kəˈlæbəreɪt/",
        partOfSpeech: "verb",
        example: "Students collaborate on group projects.",
        exampleTranslation: "Sinh viên hợp tác trong các dự án nhóm.",
        synonyms: [
            { word: "work together", level: "basic" },
            { word: "cooperate", level: "intermediate", meaning: "hợp tác" },
            { word: "partner", level: "intermediate", meaning: "hợp tác" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_043",
        word: "distinguish",
        meaning: "phân biệt",
        pronunciation: "/dɪˈstɪŋɡwɪʃ/",
        partOfSpeech: "verb",
        example: "Learn to distinguish fact from opinion.",
        exampleTranslation: "Học cách phân biệt sự thật với ý kiến.",
        synonyms: [
            { word: "differentiate", level: "intermediate", meaning: "phân biệt" },
            { word: "tell apart", level: "basic" },
            { word: "discern", level: "advanced", meaning: "nhận ra" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_044",
        word: "incentive",
        meaning: "động lực, khuyến khích",
        pronunciation: "/ɪnˈsentɪv/",
        partOfSpeech: "noun",
        example: "Scholarships provide an incentive to study hard.",
        exampleTranslation: "Học bổng là động lực để học chăm chỉ.",
        synonyms: [
            { word: "motivation", level: "intermediate", meaning: "động lực" },
            { word: "encouragement", level: "intermediate", meaning: "khuyến khích" },
            { word: "stimulus", level: "advanced", meaning: "kích thích" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_045",
        word: "attendance",
        meaning: "sự tham dự, điểm danh",
        pronunciation: "/əˈtendəns/",
        partOfSpeech: "noun",
        example: "Attendance is mandatory for all classes.",
        exampleTranslation: "Việc tham dự là bắt buộc cho tất cả các lớp.",
        synonyms: [
            { word: "presence", level: "basic", meaning: "sự có mặt" },
            { word: "participation", level: "intermediate", meaning: "tham gia" },
            { word: "turnout", level: "intermediate", meaning: "số người tham dự" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_046",
        word: "retain",
        meaning: "ghi nhớ, giữ lại",
        pronunciation: "/rɪˈteɪn/",
        partOfSpeech: "verb",
        example: "Use techniques to better retain information.",
        exampleTranslation: "Sử dụng các kỹ thuật để ghi nhớ thông tin tốt hơn.",
        synonyms: [
            { word: "remember", level: "basic", meaning: "nhớ" },
            { word: "keep", level: "basic", meaning: "giữ" },
            { word: "preserve", level: "advanced", meaning: "bảo tồn" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_047",
        word: "innovative",
        meaning: "sáng tạo, đổi mới",
        pronunciation: "/ˈɪnəvətɪv/",
        partOfSpeech: "adjective",
        example: "The school uses innovative teaching methods.",
        exampleTranslation: "Trường sử dụng các phương pháp giảng dạy sáng tạo.",
        synonyms: [
            { word: "creative", level: "basic", meaning: "sáng tạo" },
            { word: "original", level: "intermediate", meaning: "độc đáo" },
            { word: "groundbreaking", level: "advanced", meaning: "đột phá" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_048",
        word: "e-learning",
        meaning: "học trực tuyến",
        pronunciation: "/ˈiː ˈlɜːrnɪŋ/",
        partOfSpeech: "noun",
        example: "E-learning has become popular during the pandemic.",
        exampleTranslation: "Học trực tuyến đã trở nên phổ biến trong đại dịch.",
        synonyms: [
            { word: "online learning", level: "basic" },
            { word: "distance education", level: "intermediate" },
            { word: "virtual learning", level: "intermediate" },
        ],
        topic: "education",
        difficulty: "beginner",
    },
    {
        id: "edu_049",
        word: "proficiency",
        meaning: "sự thành thạo",
        pronunciation: "/prəˈfɪʃnsi/",
        partOfSpeech: "noun",
        example: "She achieved proficiency in three languages.",
        exampleTranslation: "Cô ấy đạt được sự thành thạo ba ngôn ngữ.",
        synonyms: [
            { word: "skill", level: "basic", meaning: "kỹ năng" },
            { word: "expertise", level: "advanced", meaning: "chuyên môn" },
            { word: "mastery", level: "advanced", meaning: "sự tinh thông" },
            { word: "competence", level: "intermediate", meaning: "năng lực" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
    {
        id: "edu_050",
        word: "comprehensive",
        meaning: "toàn diện, bao quát",
        pronunciation: "/ˌkɒmprɪˈhensɪv/",
        partOfSpeech: "adjective",
        example: "The course provides comprehensive coverage of the subject.",
        exampleTranslation: "Khóa học cung cấp kiến thức toàn diện về môn học.",
        synonyms: [
            { word: "complete", level: "basic", meaning: "hoàn chỉnh" },
            { word: "thorough", level: "intermediate", meaning: "kỹ lưỡng" },
            { word: "exhaustive", level: "advanced", meaning: "đầy đủ" },
            { word: "all-encompassing", level: "advanced", meaning: "bao trùm" },
        ],
        topic: "education",
        difficulty: "intermediate",
    },
];
