import { VocabularyWord } from "@/types/flashcard";

export const ENVIRONMENT_VOCABULARY: VocabularyWord[] = [
    {
        id: "env_001",
        word: "sustainable",
        meaning: "bền vững",
        pronunciation: "/səˈsteɪnəbl/",
        partOfSpeech: "adjective",
        example: "Sustainable development protects natural resources.",
        exampleTranslation: "Phát triển bền vững bảo vệ tài nguyên thiên nhiên.",
        synonyms: [
            { word: "eco-friendly", level: "basic", meaning: "thân thiện môi trường" },
            { word: "viable", level: "advanced", meaning: "khả thi" },
            { word: "renewable", level: "intermediate", meaning: "tái tạo được" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_002",
        word: "pollution",
        meaning: "ô nhiễm",
        pronunciation: "/pəˈluːʃn/",
        partOfSpeech: "noun",
        example: "Air pollution is a major concern in cities.",
        exampleTranslation: "Ô nhiễm không khí là mối lo lớn ở thành phố.",
        synonyms: [
            { word: "contamination", level: "intermediate", meaning: "sự nhiễm bẩn" },
            { word: "degradation", level: "advanced", meaning: "sự suy thoái" },
            { word: "toxicity", level: "advanced", meaning: "độc tính" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_003",
        word: "climate change",
        meaning: "biến đổi khí hậu",
        pronunciation: "/ˈklaɪmət tʃeɪndʒ/",
        partOfSpeech: "noun",
        example: "Climate change affects weather patterns worldwide.",
        exampleTranslation: "Biến đổi khí hậu ảnh hưởng đến mô hình thời tiết toàn cầu.",
        synonyms: [
            { word: "global warming", level: "basic", meaning: "nóng lên toàn cầu" },
            { word: "climate crisis", level: "intermediate" },
            { word: "environmental shift", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_004",
        word: "renewable",
        meaning: "tái tạo được",
        pronunciation: "/rɪˈnjuːəbl/",
        partOfSpeech: "adjective",
        example: "Solar power is a renewable energy source.",
        exampleTranslation: "Năng lượng mặt trời là nguồn năng lượng tái tạo.",
        synonyms: [
            { word: "sustainable", level: "intermediate", meaning: "bền vững" },
            { word: "replenishable", level: "advanced" },
            { word: "inexhaustible", level: "academic", meaning: "vô tận" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_005",
        word: "ecosystem",
        meaning: "hệ sinh thái",
        pronunciation: "/ˈiːkoʊsɪstəm/",
        partOfSpeech: "noun",
        example: "Coral reefs are delicate ecosystems.",
        exampleTranslation: "Rạn san hô là hệ sinh thái mong manh.",
        synonyms: [
            { word: "environment", level: "basic", meaning: "môi trường" },
            { word: "habitat", level: "intermediate", meaning: "môi trường sống" },
            { word: "biome", level: "academic", meaning: "quần xã sinh vật" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_006",
        word: "biodiversity",
        meaning: "đa dạng sinh học",
        pronunciation: "/ˌbaɪoʊdaɪˈvɜːrsəti/",
        partOfSpeech: "noun",
        example: "Protecting biodiversity is crucial for the planet.",
        exampleTranslation: "Bảo vệ đa dạng sinh học rất quan trọng cho hành tinh.",
        synonyms: [
            { word: "variety of life", level: "basic" },
            { word: "biological diversity", level: "intermediate" },
            { word: "ecological variety", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_007",
        word: "deforestation",
        meaning: "phá rừng",
        pronunciation: "/diːˌfɔːrɪˈsteɪʃn/",
        partOfSpeech: "noun",
        example: "Deforestation contributes to climate change.",
        exampleTranslation: "Phá rừng góp phần gây biến đổi khí hậu.",
        synonyms: [
            { word: "forest destruction", level: "basic" },
            { word: "logging", level: "intermediate", meaning: "khai thác gỗ" },
            { word: "tree clearing", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_008",
        word: "conservation",
        meaning: "bảo tồn",
        pronunciation: "/ˌkɒnsərˈveɪʃn/",
        partOfSpeech: "noun",
        example: "Wildlife conservation protects endangered species.",
        exampleTranslation: "Bảo tồn động vật hoang dã bảo vệ các loài có nguy cơ tuyệt chủng.",
        synonyms: [
            { word: "preservation", level: "intermediate", meaning: "bảo tồn" },
            { word: "protection", level: "basic", meaning: "bảo vệ" },
            { word: "safeguarding", level: "advanced", meaning: "giữ gìn" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_009",
        word: "emission",
        meaning: "sự phát thải",
        pronunciation: "/ɪˈmɪʃn/",
        partOfSpeech: "noun",
        example: "Carbon emissions must be reduced.",
        exampleTranslation: "Phát thải carbon phải được giảm.",
        synonyms: [
            { word: "discharge", level: "intermediate", meaning: "sự xả" },
            { word: "release", level: "basic", meaning: "sự phát ra" },
            { word: "output", level: "intermediate", meaning: "sản lượng" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_010",
        word: "recycle",
        meaning: "tái chế",
        pronunciation: "/riːˈsaɪkl/",
        partOfSpeech: "verb",
        example: "We should recycle plastic and paper.",
        exampleTranslation: "Chúng ta nên tái chế nhựa và giấy.",
        synonyms: [
            { word: "reuse", level: "basic", meaning: "tái sử dụng" },
            { word: "repurpose", level: "intermediate", meaning: "sử dụng lại" },
            { word: "reprocess", level: "advanced", meaning: "tái xử lý" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_011",
        word: "endangered",
        meaning: "có nguy cơ tuyệt chủng",
        pronunciation: "/ɪnˈdeɪndʒərd/",
        partOfSpeech: "adjective",
        example: "Tigers are an endangered species.",
        exampleTranslation: "Hổ là loài có nguy cơ tuyệt chủng.",
        synonyms: [
            { word: "threatened", level: "intermediate", meaning: "bị đe dọa" },
            { word: "at risk", level: "basic" },
            { word: "vulnerable", level: "advanced", meaning: "dễ bị tổn thương" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_012",
        word: "carbon footprint",
        meaning: "dấu chân carbon",
        pronunciation: "/ˈkɑːrbən ˈfʊtprɪnt/",
        partOfSpeech: "noun",
        example: "We should all try to reduce our carbon footprint.",
        exampleTranslation: "Tất cả chúng ta nên cố gắng giảm dấu chân carbon.",
        synonyms: [
            { word: "environmental impact", level: "intermediate" },
            { word: "carbon emissions", level: "intermediate" },
            { word: "ecological footprint", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_013",
        word: "greenhouse effect",
        meaning: "hiệu ứng nhà kính",
        pronunciation: "/ˈɡriːnhaʊs ɪˈfekt/",
        partOfSpeech: "noun",
        example: "The greenhouse effect causes global temperatures to rise.",
        exampleTranslation: "Hiệu ứng nhà kính làm nhiệt độ toàn cầu tăng.",
        synonyms: [
            { word: "global warming", level: "basic", meaning: "nóng lên toàn cầu" },
            { word: "atmospheric heating", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_014",
        word: "habitat",
        meaning: "môi trường sống",
        pronunciation: "/ˈhæbɪtæt/",
        partOfSpeech: "noun",
        example: "Wetlands provide habitat for many bird species.",
        exampleTranslation: "Vùng đất ngập nước cung cấp môi trường sống cho nhiều loài chim.",
        synonyms: [
            { word: "environment", level: "basic", meaning: "môi trường" },
            { word: "territory", level: "intermediate", meaning: "lãnh thổ" },
            { word: "dwelling place", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_015",
        word: "erosion",
        meaning: "xói mòn",
        pronunciation: "/ɪˈroʊʒn/",
        partOfSpeech: "noun",
        example: "Soil erosion is a serious environmental problem.",
        exampleTranslation: "Xói mòn đất là vấn đề môi trường nghiêm trọng.",
        synonyms: [
            { word: "wearing away", level: "basic" },
            { word: "degradation", level: "advanced", meaning: "suy thoái" },
            { word: "deterioration", level: "advanced", meaning: "sự xuống cấp" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_016",
        word: "fossil fuel",
        meaning: "nhiên liệu hóa thạch",
        pronunciation: "/ˈfɒsl ˈfjuːəl/",
        partOfSpeech: "noun",
        example: "Burning fossil fuels releases carbon dioxide.",
        exampleTranslation: "Đốt nhiên liệu hóa thạch giải phóng carbon dioxide.",
        synonyms: [
            { word: "petroleum", level: "intermediate", meaning: "dầu mỏ" },
            { word: "coal", level: "basic", meaning: "than đá" },
            { word: "natural gas", level: "intermediate", meaning: "khí tự nhiên" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_017",
        word: "ozone layer",
        meaning: "tầng ozone",
        pronunciation: "/ˈoʊzoʊn ˈleɪər/",
        partOfSpeech: "noun",
        example: "The ozone layer protects us from UV radiation.",
        exampleTranslation: "Tầng ozone bảo vệ chúng ta khỏi bức xạ tia cực tím.",
        synonyms: [
            { word: "ozone shield", level: "intermediate" },
            { word: "atmospheric layer", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_018",
        word: "contaminate",
        meaning: "làm ô nhiễm",
        pronunciation: "/kənˈtæmɪneɪt/",
        partOfSpeech: "verb",
        example: "Industrial waste can contaminate water supplies.",
        exampleTranslation: "Chất thải công nghiệp có thể làm ô nhiễm nguồn nước.",
        synonyms: [
            { word: "pollute", level: "basic", meaning: "làm ô nhiễm" },
            { word: "taint", level: "advanced", meaning: "làm hỏng" },
            { word: "poison", level: "intermediate", meaning: "đầu độc" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_019",
        word: "drought",
        meaning: "hạn hán",
        pronunciation: "/draʊt/",
        partOfSpeech: "noun",
        example: "The drought destroyed crops across the region.",
        exampleTranslation: "Hạn hán đã phá hủy mùa màng khắp vùng.",
        synonyms: [
            { word: "dry spell", level: "basic" },
            { word: "aridity", level: "advanced", meaning: "sự khô cằn" },
            { word: "water shortage", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_020",
        word: "flood",
        meaning: "lũ lụt",
        pronunciation: "/flʌd/",
        partOfSpeech: "noun",
        example: "Heavy rains caused floods in many areas.",
        exampleTranslation: "Mưa lớn gây ra lũ lụt ở nhiều khu vực.",
        synonyms: [
            { word: "deluge", level: "advanced", meaning: "trận lụt lớn" },
            { word: "inundation", level: "academic", meaning: "sự ngập" },
            { word: "overflow", level: "intermediate", meaning: "tràn" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_021",
        word: "organic",
        meaning: "hữu cơ",
        pronunciation: "/ɔːrˈɡænɪk/",
        partOfSpeech: "adjective",
        example: "Organic farming avoids synthetic chemicals.",
        exampleTranslation: "Canh tác hữu cơ tránh hóa chất tổng hợp.",
        synonyms: [
            { word: "natural", level: "basic", meaning: "tự nhiên" },
            { word: "chemical-free", level: "intermediate" },
            { word: "pesticide-free", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_022",
        word: "waste",
        meaning: "rác thải, chất thải",
        pronunciation: "/weɪst/",
        partOfSpeech: "noun",
        example: "Proper waste management is essential.",
        exampleTranslation: "Quản lý chất thải đúng cách là cần thiết.",
        synonyms: [
            { word: "garbage", level: "basic", meaning: "rác" },
            { word: "refuse", level: "intermediate", meaning: "rác rưởi" },
            { word: "debris", level: "advanced", meaning: "mảnh vụn" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_023",
        word: "toxic",
        meaning: "độc hại",
        pronunciation: "/ˈtɒksɪk/",
        partOfSpeech: "adjective",
        example: "Toxic chemicals can harm the environment.",
        exampleTranslation: "Hóa chất độc hại có thể gây hại môi trường.",
        synonyms: [
            { word: "poisonous", level: "basic", meaning: "có độc" },
            { word: "hazardous", level: "intermediate", meaning: "nguy hiểm" },
            { word: "noxious", level: "advanced", meaning: "độc hại" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_024",
        word: "wildlife",
        meaning: "động vật hoang dã",
        pronunciation: "/ˈwaɪldlaɪf/",
        partOfSpeech: "noun",
        example: "The national park protects local wildlife.",
        exampleTranslation: "Vườn quốc gia bảo vệ động vật hoang dã địa phương.",
        synonyms: [
            { word: "fauna", level: "advanced", meaning: "hệ động vật" },
            { word: "wild animals", level: "basic" },
            { word: "native species", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_025",
        word: "preserve",
        meaning: "bảo tồn, giữ gìn",
        pronunciation: "/prɪˈzɜːrv/",
        partOfSpeech: "verb",
        example: "We must preserve natural habitats.",
        exampleTranslation: "Chúng ta phải bảo tồn môi trường sống tự nhiên.",
        synonyms: [
            { word: "protect", level: "basic", meaning: "bảo vệ" },
            { word: "conserve", level: "intermediate", meaning: "bảo tồn" },
            { word: "safeguard", level: "advanced", meaning: "bảo vệ" },
            { word: "maintain", level: "intermediate", meaning: "duy trì" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_026",
        word: "extinction",
        meaning: "sự tuyệt chủng",
        pronunciation: "/ɪkˈstɪŋkʃn/",
        partOfSpeech: "noun",
        example: "Many species face extinction due to habitat loss.",
        exampleTranslation: "Nhiều loài đối mặt với tuyệt chủng do mất môi trường sống.",
        synonyms: [
            { word: "dying out", level: "basic" },
            { word: "disappearance", level: "intermediate", meaning: "sự biến mất" },
            { word: "annihilation", level: "academic", meaning: "sự tiêu diệt" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_027",
        word: "reforestation",
        meaning: "tái trồng rừng",
        pronunciation: "/riːˌfɔːrɪˈsteɪʃn/",
        partOfSpeech: "noun",
        example: "Reforestation helps combat climate change.",
        exampleTranslation: "Tái trồng rừng giúp chống biến đổi khí hậu.",
        synonyms: [
            { word: "tree planting", level: "basic" },
            { word: "afforestation", level: "advanced", meaning: "trồng rừng mới" },
            { word: "forest restoration", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_028",
        word: "solar energy",
        meaning: "năng lượng mặt trời",
        pronunciation: "/ˈsoʊlər ˈenərdʒi/",
        partOfSpeech: "noun",
        example: "Solar energy is becoming more affordable.",
        exampleTranslation: "Năng lượng mặt trời đang trở nên rẻ hơn.",
        synonyms: [
            { word: "solar power", level: "basic" },
            { word: "photovoltaic energy", level: "academic" },
            { word: "sun power", level: "basic" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_029",
        word: "wind turbine",
        meaning: "tua-bin gió",
        pronunciation: "/wɪnd ˈtɜːrbaɪn/",
        partOfSpeech: "noun",
        example: "Wind turbines generate clean electricity.",
        exampleTranslation: "Tua-bin gió tạo ra điện sạch.",
        synonyms: [
            { word: "windmill", level: "basic", meaning: "cối xay gió" },
            { word: "wind generator", level: "intermediate" },
            { word: "aerogenerator", level: "academic" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_030",
        word: "natural resources",
        meaning: "tài nguyên thiên nhiên",
        pronunciation: "/ˈnætʃrəl rɪˈsɔːrsɪz/",
        partOfSpeech: "noun",
        example: "We must use natural resources responsibly.",
        exampleTranslation: "Chúng ta phải sử dụng tài nguyên thiên nhiên có trách nhiệm.",
        synonyms: [
            { word: "raw materials", level: "intermediate", meaning: "nguyên liệu thô" },
            { word: "natural assets", level: "advanced" },
            { word: "environmental resources", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_031",
        word: "sustainable development",
        meaning: "phát triển bền vững",
        pronunciation: "/səˈsteɪnəbl dɪˈveləpmənt/",
        partOfSpeech: "noun",
        example: "Sustainable development balances growth and environment.",
        exampleTranslation: "Phát triển bền vững cân bằng giữa tăng trưởng và môi trường.",
        synonyms: [
            { word: "green growth", level: "intermediate" },
            { word: "eco-development", level: "advanced" },
            { word: "responsible development", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_032",
        word: "landfill",
        meaning: "bãi chôn lấp rác",
        pronunciation: "/ˈlændfɪl/",
        partOfSpeech: "noun",
        example: "Landfills are filling up quickly.",
        exampleTranslation: "Các bãi chôn lấp đang đầy nhanh chóng.",
        synonyms: [
            { word: "dump", level: "basic", meaning: "bãi rác" },
            { word: "waste site", level: "intermediate" },
            { word: "rubbish tip", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_033",
        word: "carbon neutral",
        meaning: "trung hòa carbon",
        pronunciation: "/ˈkɑːrbən ˈnjuːtrəl/",
        partOfSpeech: "adjective",
        example: "The company aims to be carbon neutral by 2030.",
        exampleTranslation: "Công ty đặt mục tiêu trung hòa carbon vào năm 2030.",
        synonyms: [
            { word: "net zero", level: "intermediate" },
            { word: "climate neutral", level: "advanced" },
            { word: "carbon balanced", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "advanced",
    },
    {
        id: "env_034",
        word: "ice cap",
        meaning: "chỏm băng",
        pronunciation: "/aɪs kæp/",
        partOfSpeech: "noun",
        example: "The ice caps are melting at an alarming rate.",
        exampleTranslation: "Các chỏm băng đang tan với tốc độ đáng báo động.",
        synonyms: [
            { word: "polar ice", level: "basic" },
            { word: "glacier", level: "intermediate", meaning: "sông băng" },
            { word: "ice sheet", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_035",
        word: "biodegradable",
        meaning: "có thể phân hủy sinh học",
        pronunciation: "/ˌbaɪoʊdɪˈɡreɪdəbl/",
        partOfSpeech: "adjective",
        example: "Biodegradable packaging reduces waste.",
        exampleTranslation: "Bao bì phân hủy sinh học giảm rác thải.",
        synonyms: [
            { word: "decomposable", level: "advanced" },
            { word: "eco-friendly", level: "intermediate" },
            { word: "compostable", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_036",
        word: "ecology",
        meaning: "sinh thái học",
        pronunciation: "/ɪˈkɒlədʒi/",
        partOfSpeech: "noun",
        example: "She studies marine ecology.",
        exampleTranslation: "Cô ấy nghiên cứu sinh thái học biển.",
        synonyms: [
            { word: "environmental science", level: "intermediate" },
            { word: "bionomics", level: "academic" },
            { word: "natural science", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_037",
        word: "energy efficiency",
        meaning: "hiệu quả năng lượng",
        pronunciation: "/ˈenərdʒi ɪˈfɪʃnsi/",
        partOfSpeech: "noun",
        example: "Energy efficiency reduces electricity costs.",
        exampleTranslation: "Hiệu quả năng lượng giảm chi phí điện.",
        synonyms: [
            { word: "power saving", level: "basic" },
            { word: "energy conservation", level: "intermediate" },
            { word: "resource optimization", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_038",
        word: "environmental impact",
        meaning: "tác động môi trường",
        pronunciation: "/ɪnˌvaɪrənˈmentl ˈɪmpækt/",
        partOfSpeech: "noun",
        example: "We assess the environmental impact of new projects.",
        exampleTranslation: "Chúng tôi đánh giá tác động môi trường của dự án mới.",
        synonyms: [
            { word: "ecological effect", level: "intermediate" },
            { word: "green footprint", level: "intermediate" },
            { word: "environmental consequence", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_039",
        word: "pesticide",
        meaning: "thuốc trừ sâu",
        pronunciation: "/ˈpestɪsaɪd/",
        partOfSpeech: "noun",
        example: "Organic farmers avoid using pesticides.",
        exampleTranslation: "Nông dân hữu cơ tránh sử dụng thuốc trừ sâu.",
        synonyms: [
            { word: "insecticide", level: "intermediate", meaning: "thuốc diệt côn trùng" },
            { word: "herbicide", level: "intermediate", meaning: "thuốc diệt cỏ" },
            { word: "chemical spray", level: "basic" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_040",
        word: "tropical rainforest",
        meaning: "rừng nhiệt đới",
        pronunciation: "/ˈtrɒpɪkl ˈreɪnfɔːrɪst/",
        partOfSpeech: "noun",
        example: "Tropical rainforests are rich in biodiversity.",
        exampleTranslation: "Rừng nhiệt đới giàu đa dạng sinh học.",
        synonyms: [
            { word: "jungle", level: "basic", meaning: "rừng rậm" },
            { word: "equatorial forest", level: "advanced" },
            { word: "tropical jungle", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_041",
        word: "atmosphere",
        meaning: "khí quyển",
        pronunciation: "/ˈætməsfɪr/",
        partOfSpeech: "noun",
        example: "Greenhouse gases trap heat in the atmosphere.",
        exampleTranslation: "Khí nhà kính giữ nhiệt trong khí quyển.",
        synonyms: [
            { word: "air", level: "basic", meaning: "không khí" },
            { word: "sky", level: "basic", meaning: "bầu trời" },
            { word: "stratosphere", level: "academic", meaning: "tầng bình lưu" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_042",
        word: "eco-friendly",
        meaning: "thân thiện với môi trường",
        pronunciation: "/ˌiːkoʊ ˈfrendli/",
        partOfSpeech: "adjective",
        example: "Consumers prefer eco-friendly products.",
        exampleTranslation: "Người tiêu dùng thích sản phẩm thân thiện môi trường.",
        synonyms: [
            { word: "green", level: "basic", meaning: "xanh" },
            { word: "environmentally friendly", level: "intermediate" },
            { word: "sustainable", level: "intermediate", meaning: "bền vững" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_043",
        word: "smog",
        meaning: "sương mù ô nhiễm",
        pronunciation: "/smɒɡ/",
        partOfSpeech: "noun",
        example: "City smog causes respiratory problems.",
        exampleTranslation: "Sương mù ô nhiễm thành phố gây vấn đề hô hấp.",
        synonyms: [
            { word: "haze", level: "intermediate", meaning: "sương mờ" },
            { word: "air pollution", level: "basic" },
            { word: "polluted fog", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_044",
        word: "degradation",
        meaning: "sự suy thoái",
        pronunciation: "/ˌdeɡrəˈdeɪʃn/",
        partOfSpeech: "noun",
        example: "Environmental degradation threatens future generations.",
        exampleTranslation: "Suy thoái môi trường đe dọa các thế hệ tương lai.",
        synonyms: [
            { word: "deterioration", level: "advanced", meaning: "sự xuống cấp" },
            { word: "decline", level: "intermediate", meaning: "sự suy giảm" },
            { word: "destruction", level: "intermediate", meaning: "sự phá hủy" },
        ],
        topic: "environment",
        difficulty: "advanced",
    },
    {
        id: "env_045",
        word: "carbon dioxide",
        meaning: "khí carbon dioxide",
        pronunciation: "/ˈkɑːrbən daɪˈɒksaɪd/",
        partOfSpeech: "noun",
        example: "Trees absorb carbon dioxide from the air.",
        exampleTranslation: "Cây hấp thụ khí carbon dioxide từ không khí.",
        synonyms: [
            { word: "CO2", level: "basic" },
            { word: "greenhouse gas", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "beginner",
    },
    {
        id: "env_046",
        word: "acid rain",
        meaning: "mưa axit",
        pronunciation: "/ˈæsɪd reɪn/",
        partOfSpeech: "noun",
        example: "Acid rain damages buildings and forests.",
        exampleTranslation: "Mưa axit làm hư hại các tòa nhà và rừng.",
        synonyms: [
            { word: "acidic precipitation", level: "advanced" },
            { word: "chemical rain", level: "intermediate" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_047",
        word: "marine",
        meaning: "thuộc về biển",
        pronunciation: "/məˈriːn/",
        partOfSpeech: "adjective",
        example: "Marine ecosystems are under threat.",
        exampleTranslation: "Hệ sinh thái biển đang bị đe dọa.",
        synonyms: [
            { word: "ocean", level: "basic", meaning: "đại dương" },
            { word: "sea", level: "basic", meaning: "biển" },
            { word: "aquatic", level: "intermediate", meaning: "thủy sinh" },
            { word: "nautical", level: "advanced", meaning: "hàng hải" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_048",
        word: "fertilizer",
        meaning: "phân bón",
        pronunciation: "/ˈfɜːrtəlaɪzər/",
        partOfSpeech: "noun",
        example: "Excessive fertilizer use can pollute water.",
        exampleTranslation: "Sử dụng phân bón quá mức có thể làm ô nhiễm nước.",
        synonyms: [
            { word: "plant food", level: "basic" },
            { word: "nutrient", level: "intermediate", meaning: "chất dinh dưỡng" },
            { word: "soil enhancer", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "intermediate",
    },
    {
        id: "env_049",
        word: "ecosystem services",
        meaning: "dịch vụ hệ sinh thái",
        pronunciation: "/ˈiːkoʊsɪstəm ˈsɜːrvɪsɪz/",
        partOfSpeech: "noun",
        example: "Forests provide vital ecosystem services.",
        exampleTranslation: "Rừng cung cấp các dịch vụ hệ sinh thái quan trọng.",
        synonyms: [
            { word: "natural benefits", level: "intermediate" },
            { word: "environmental services", level: "intermediate" },
            { word: "ecological functions", level: "advanced" },
        ],
        topic: "environment",
        difficulty: "advanced",
    },
    {
        id: "env_050",
        word: "desertification",
        meaning: "sa mạc hóa",
        pronunciation: "/dɪˌzɜːrtɪfɪˈkeɪʃn/",
        partOfSpeech: "noun",
        example: "Desertification is turning farmland into desert.",
        exampleTranslation: "Sa mạc hóa đang biến đất nông nghiệp thành sa mạc.",
        synonyms: [
            { word: "land degradation", level: "advanced" },
            { word: "soil erosion", level: "intermediate" },
            { word: "aridification", level: "academic" },
        ],
        topic: "environment",
        difficulty: "advanced",
    },
];
