import { VocabularyWord } from "@/types/flashcard";

export const HEALTH_VOCABULARY: VocabularyWord[] = [
    {
        id: "health_001",
        word: "healthy",
        meaning: "khỏe mạnh, lành mạnh",
        pronunciation: "/ˈhelθi/",
        partOfSpeech: "adjective",
        example: "A healthy diet includes plenty of fruits and vegetables.",
        exampleTranslation: "Một chế độ ăn lành mạnh bao gồm nhiều trái cây và rau củ.",
        synonyms: [
            { word: "fit", level: "basic", meaning: "cân đối, khỏe" },
            { word: "well", level: "basic", meaning: "khỏe" },
            { word: "robust", level: "advanced", meaning: "cường tráng" },
            { word: "flourishing", level: "academic", meaning: "sung túc" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_002",
        word: "exercise",
        meaning: "tập thể dục",
        pronunciation: "/ˈeksərsaɪz/",
        partOfSpeech: "noun",
        example: "Regular exercise can improve mental health.",
        exampleTranslation: "Tập thể dục đều đặn có thể cải thiện sức khỏe tinh thần.",
        synonyms: [
            { word: "workout", level: "basic", meaning: "buổi tập" },
            { word: "physical activity", level: "intermediate" },
            { word: "training", level: "intermediate", meaning: "luyện tập" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_003",
        word: "nutrition",
        meaning: "dinh dưỡng",
        pronunciation: "/nuːˈtrɪʃn/",
        partOfSpeech: "noun",
        example: "Good nutrition is essential for child development.",
        exampleTranslation: "Dinh dưỡng tốt là cần thiết cho sự phát triển của trẻ.",
        synonyms: [
            { word: "diet", level: "basic", meaning: "chế độ ăn" },
            { word: "nourishment", level: "advanced", meaning: "sự nuôi dưỡng" },
            { word: "sustenance", level: "academic", meaning: "thức ăn nuôi sống" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_004",
        word: "symptom",
        meaning: "triệu chứng",
        pronunciation: "/ˈsɪmptəm/",
        partOfSpeech: "noun",
        example: "Fever is a common symptom of infection.",
        exampleTranslation: "Sốt là triệu chứng phổ biến của nhiễm trùng.",
        synonyms: [
            { word: "sign", level: "basic", meaning: "dấu hiệu" },
            { word: "indication", level: "intermediate", meaning: "chỉ dấu" },
            { word: "manifestation", level: "academic", meaning: "biểu hiện" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_005",
        word: "treatment",
        meaning: "điều trị, chữa trị",
        pronunciation: "/ˈtriːtmənt/",
        partOfSpeech: "noun",
        example: "The patient responded well to the treatment.",
        exampleTranslation: "Bệnh nhân đáp ứng tốt với điều trị.",
        synonyms: [
            { word: "cure", level: "basic", meaning: "cách chữa" },
            { word: "therapy", level: "intermediate", meaning: "liệu pháp" },
            { word: "remedy", level: "advanced", meaning: "phương thuốc" },
            { word: "intervention", level: "academic", meaning: "can thiệp" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_006",
        word: "disease",
        meaning: "bệnh, căn bệnh",
        pronunciation: "/dɪˈziːz/",
        partOfSpeech: "noun",
        example: "Heart disease is a leading cause of death.",
        exampleTranslation: "Bệnh tim là nguyên nhân hàng đầu gây tử vong.",
        synonyms: [
            { word: "illness", level: "basic", meaning: "bệnh tật" },
            { word: "condition", level: "intermediate", meaning: "tình trạng" },
            { word: "ailment", level: "advanced", meaning: "chứng bệnh" },
            { word: "malady", level: "academic", meaning: "căn bệnh" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_007",
        word: "prevent",
        meaning: "ngăn ngừa, phòng tránh",
        pronunciation: "/prɪˈvent/",
        partOfSpeech: "verb",
        example: "Vaccines help prevent infectious diseases.",
        exampleTranslation: "Vắc-xin giúp ngăn ngừa các bệnh truyền nhiễm.",
        synonyms: [
            { word: "stop", level: "basic", meaning: "ngừng" },
            { word: "avoid", level: "basic", meaning: "tránh" },
            { word: "avert", level: "advanced", meaning: "ngăn chặn" },
            { word: "preclude", level: "academic", meaning: "loại trừ" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_008",
        word: "mental health",
        meaning: "sức khỏe tinh thần",
        pronunciation: "/ˈmentl helθ/",
        partOfSpeech: "noun",
        example: "Mental health is as important as physical health.",
        exampleTranslation: "Sức khỏe tinh thần quan trọng như sức khỏe thể chất.",
        synonyms: [
            { word: "psychological wellbeing", level: "advanced" },
            { word: "emotional health", level: "intermediate" },
            { word: "psychiatric wellness", level: "academic" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_009",
        word: "obesity",
        meaning: "béo phì",
        pronunciation: "/oʊˈbiːsəti/",
        partOfSpeech: "noun",
        example: "Obesity increases the risk of diabetes.",
        exampleTranslation: "Béo phì làm tăng nguy cơ tiểu đường.",
        synonyms: [
            { word: "overweight", level: "basic", meaning: "thừa cân" },
            { word: "corpulence", level: "academic", meaning: "sự béo phì" },
            { word: "excess weight", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_010",
        word: "immune system",
        meaning: "hệ miễn dịch",
        pronunciation: "/ɪˈmjuːn ˈsɪstəm/",
        partOfSpeech: "noun",
        example: "A strong immune system fights off infections.",
        exampleTranslation: "Hệ miễn dịch mạnh chống lại các bệnh nhiễm trùng.",
        synonyms: [
            { word: "body's defenses", level: "intermediate" },
            { word: "immunological system", level: "academic" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_011",
        word: "diagnosis",
        meaning: "chẩn đoán",
        pronunciation: "/ˌdaɪəɡˈnoʊsɪs/",
        partOfSpeech: "noun",
        example: "Early diagnosis can save lives.",
        exampleTranslation: "Chẩn đoán sớm có thể cứu sống mạng người.",
        synonyms: [
            { word: "identification", level: "intermediate", meaning: "nhận dạng" },
            { word: "detection", level: "intermediate", meaning: "phát hiện" },
            { word: "assessment", level: "advanced", meaning: "đánh giá" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_012",
        word: "recovery",
        meaning: "sự hồi phục",
        pronunciation: "/rɪˈkʌvəri/",
        partOfSpeech: "noun",
        example: "The patient made a full recovery.",
        exampleTranslation: "Bệnh nhân đã hồi phục hoàn toàn.",
        synonyms: [
            { word: "healing", level: "basic", meaning: "chữa lành" },
            { word: "recuperation", level: "advanced", meaning: "sự bình phục" },
            { word: "convalescence", level: "academic", meaning: "thời kỳ dưỡng bệnh" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_013",
        word: "chronic",
        meaning: "mãn tính, kinh niên",
        pronunciation: "/ˈkrɒnɪk/",
        partOfSpeech: "adjective",
        example: "Chronic pain affects millions of people.",
        exampleTranslation: "Đau mãn tính ảnh hưởng đến hàng triệu người.",
        synonyms: [
            { word: "long-term", level: "basic", meaning: "dài hạn" },
            { word: "persistent", level: "intermediate", meaning: "dai dẳng" },
            { word: "prolonged", level: "advanced", meaning: "kéo dài" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_014",
        word: "contagious",
        meaning: "lây nhiễm, truyền nhiễm",
        pronunciation: "/kənˈteɪdʒəs/",
        partOfSpeech: "adjective",
        example: "The flu is highly contagious.",
        exampleTranslation: "Bệnh cúm rất dễ lây.",
        synonyms: [
            { word: "infectious", level: "intermediate", meaning: "truyền nhiễm" },
            { word: "communicable", level: "advanced", meaning: "có thể lây truyền" },
            { word: "transmissible", level: "academic", meaning: "có thể truyền" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_015",
        word: "medication",
        meaning: "thuốc, dược phẩm",
        pronunciation: "/ˌmedɪˈkeɪʃn/",
        partOfSpeech: "noun",
        example: "Take your medication as prescribed.",
        exampleTranslation: "Uống thuốc theo chỉ định.",
        synonyms: [
            { word: "medicine", level: "basic", meaning: "thuốc" },
            { word: "drug", level: "basic", meaning: "dược phẩm" },
            { word: "pharmaceutical", level: "advanced", meaning: "dược phẩm" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_016",
        word: "well-being",
        meaning: "sự khỏe mạnh, hạnh phúc",
        pronunciation: "/ˌwel ˈbiːɪŋ/",
        partOfSpeech: "noun",
        example: "Exercise contributes to overall well-being.",
        exampleTranslation: "Tập thể dục góp phần vào sức khỏe tổng thể.",
        synonyms: [
            { word: "health", level: "basic", meaning: "sức khỏe" },
            { word: "welfare", level: "intermediate", meaning: "phúc lợi" },
            { word: "prosperity", level: "advanced", meaning: "thịnh vượng" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_017",
        word: "stress",
        meaning: "căng thẳng, áp lực",
        pronunciation: "/stres/",
        partOfSpeech: "noun",
        example: "Chronic stress can lead to health problems.",
        exampleTranslation: "Căng thẳng mãn tính có thể dẫn đến các vấn đề sức khỏe.",
        synonyms: [
            { word: "pressure", level: "basic", meaning: "áp lực" },
            { word: "tension", level: "intermediate", meaning: "sự căng thẳng" },
            { word: "strain", level: "advanced", meaning: "sự căng" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_018",
        word: "vaccine",
        meaning: "vắc-xin",
        pronunciation: "/vækˈsiːn/",
        partOfSpeech: "noun",
        example: "The vaccine has been proven safe and effective.",
        exampleTranslation: "Vắc-xin đã được chứng minh an toàn và hiệu quả.",
        synonyms: [
            { word: "immunization", level: "intermediate", meaning: "tiêm chủng" },
            { word: "inoculation", level: "advanced", meaning: "sự tiêm phòng" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_019",
        word: "sedentary",
        meaning: "ít vận động, ngồi nhiều",
        pronunciation: "/ˈsedntəri/",
        partOfSpeech: "adjective",
        example: "A sedentary lifestyle increases health risks.",
        exampleTranslation: "Lối sống ít vận động làm tăng nguy cơ sức khỏe.",
        synonyms: [
            { word: "inactive", level: "basic", meaning: "không hoạt động" },
            { word: "stationary", level: "intermediate", meaning: "đứng yên" },
            { word: "desk-bound", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_020",
        word: "dietary",
        meaning: "thuộc về chế độ ăn",
        pronunciation: "/ˈdaɪətəri/",
        partOfSpeech: "adjective",
        example: "Dietary changes can improve cholesterol levels.",
        exampleTranslation: "Thay đổi chế độ ăn có thể cải thiện mức cholesterol.",
        synonyms: [
            { word: "nutritional", level: "intermediate", meaning: "dinh dưỡng" },
            { word: "food-related", level: "basic" },
            { word: "alimentary", level: "academic" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_021",
        word: "fatigue",
        meaning: "mệt mỏi, kiệt sức",
        pronunciation: "/fəˈtiːɡ/",
        partOfSpeech: "noun",
        example: "Fatigue is a common symptom of iron deficiency.",
        exampleTranslation: "Mệt mỏi là triệu chứng phổ biến của thiếu sắt.",
        synonyms: [
            { word: "tiredness", level: "basic", meaning: "sự mệt" },
            { word: "exhaustion", level: "intermediate", meaning: "kiệt sức" },
            { word: "weariness", level: "advanced", meaning: "sự mệt mỏi" },
            { word: "lethargy", level: "academic", meaning: "hôn mê" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_022",
        word: "allergy",
        meaning: "dị ứng",
        pronunciation: "/ˈælərdʒi/",
        partOfSpeech: "noun",
        example: "Food allergies can be life-threatening.",
        exampleTranslation: "Dị ứng thực phẩm có thể đe dọa tính mạng.",
        synonyms: [
            { word: "sensitivity", level: "intermediate", meaning: "sự nhạy cảm" },
            { word: "hypersensitivity", level: "academic" },
            { word: "intolerance", level: "advanced", meaning: "không dung nạp" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_023",
        word: "inflammation",
        meaning: "viêm, sưng viêm",
        pronunciation: "/ˌɪnfləˈmeɪʃn/",
        partOfSpeech: "noun",
        example: "Inflammation is the body's response to injury.",
        exampleTranslation: "Viêm là phản ứng của cơ thể với chấn thương.",
        synonyms: [
            { word: "swelling", level: "basic", meaning: "sưng" },
            { word: "irritation", level: "intermediate", meaning: "kích ứng" },
            { word: "redness", level: "basic", meaning: "đỏ" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_024",
        word: "hydration",
        meaning: "sự cung cấp nước",
        pronunciation: "/haɪˈdreɪʃn/",
        partOfSpeech: "noun",
        example: "Proper hydration is important during exercise.",
        exampleTranslation: "Cung cấp nước đúng cách rất quan trọng khi tập thể dục.",
        synonyms: [
            { word: "water intake", level: "basic" },
            { word: "fluid balance", level: "advanced" },
            { word: "rehydration", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_025",
        word: "metabolism",
        meaning: "sự trao đổi chất",
        pronunciation: "/məˈtæbəlɪzəm/",
        partOfSpeech: "noun",
        example: "Exercise can boost your metabolism.",
        exampleTranslation: "Tập thể dục có thể tăng cường trao đổi chất.",
        synonyms: [
            { word: "metabolic rate", level: "intermediate" },
            { word: "body chemistry", level: "advanced" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_026",
        word: "insomnia",
        meaning: "mất ngủ",
        pronunciation: "/ɪnˈsɒmniə/",
        partOfSpeech: "noun",
        example: "Stress often leads to insomnia.",
        exampleTranslation: "Căng thẳng thường dẫn đến mất ngủ.",
        synonyms: [
            { word: "sleeplessness", level: "basic" },
            { word: "sleep disorder", level: "intermediate" },
            { word: "sleep deprivation", level: "advanced" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_027",
        word: "balanced",
        meaning: "cân bằng",
        pronunciation: "/ˈbælənst/",
        partOfSpeech: "adjective",
        example: "A balanced diet is key to good health.",
        exampleTranslation: "Chế độ ăn cân bằng là chìa khóa cho sức khỏe tốt.",
        synonyms: [
            { word: "proportioned", level: "intermediate", meaning: "cân đối" },
            { word: "well-rounded", level: "intermediate", meaning: "toàn diện" },
            { word: "harmonious", level: "advanced", meaning: "hài hòa" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_028",
        word: "supplement",
        meaning: "thực phẩm bổ sung",
        pronunciation: "/ˈsʌplɪmənt/",
        partOfSpeech: "noun",
        example: "Many people take vitamin supplements.",
        exampleTranslation: "Nhiều người uống thực phẩm bổ sung vitamin.",
        synonyms: [
            { word: "addition", level: "basic", meaning: "bổ sung" },
            { word: "enhancement", level: "advanced", meaning: "tăng cường" },
            { word: "nutritional aid", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_029",
        word: "depression",
        meaning: "trầm cảm",
        pronunciation: "/dɪˈpreʃn/",
        partOfSpeech: "noun",
        example: "Depression affects millions of people worldwide.",
        exampleTranslation: "Trầm cảm ảnh hưởng đến hàng triệu người trên thế giới.",
        synonyms: [
            { word: "sadness", level: "basic", meaning: "nỗi buồn" },
            { word: "melancholy", level: "advanced", meaning: "u sầu" },
            { word: "despondency", level: "academic", meaning: "sự chán nản" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_030",
        word: "anxiety",
        meaning: "lo âu, lo lắng",
        pronunciation: "/æŋˈzaɪəti/",
        partOfSpeech: "noun",
        example: "Anxiety disorders are very common.",
        exampleTranslation: "Rối loạn lo âu rất phổ biến.",
        synonyms: [
            { word: "worry", level: "basic", meaning: "lo lắng" },
            { word: "nervousness", level: "intermediate", meaning: "hồi hộp" },
            { word: "apprehension", level: "advanced", meaning: "lo ngại" },
            { word: "unease", level: "intermediate", meaning: "bất an" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_031",
        word: "cardiovascular",
        meaning: "tim mạch",
        pronunciation: "/ˌkɑːrdioʊˈvæskjələr/",
        partOfSpeech: "adjective",
        example: "Cardiovascular exercise strengthens the heart.",
        exampleTranslation: "Tập luyện tim mạch làm tim khỏe mạnh hơn.",
        synonyms: [
            { word: "heart-related", level: "basic" },
            { word: "cardiac", level: "advanced", meaning: "thuộc về tim" },
            { word: "circulatory", level: "advanced", meaning: "tuần hoàn" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_032",
        word: "therapy",
        meaning: "liệu pháp, trị liệu",
        pronunciation: "/ˈθerəpi/",
        partOfSpeech: "noun",
        example: "Physical therapy helped her recover from the injury.",
        exampleTranslation: "Vật lý trị liệu giúp cô ấy hồi phục sau chấn thương.",
        synonyms: [
            { word: "treatment", level: "basic", meaning: "điều trị" },
            { word: "rehabilitation", level: "advanced", meaning: "phục hồi chức năng" },
            { word: "counseling", level: "intermediate", meaning: "tư vấn" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_033",
        word: "hygiene",
        meaning: "vệ sinh",
        pronunciation: "/ˈhaɪdʒiːn/",
        partOfSpeech: "noun",
        example: "Good hygiene prevents the spread of germs.",
        exampleTranslation: "Vệ sinh tốt ngăn chặn sự lây lan của vi trùng.",
        synonyms: [
            { word: "cleanliness", level: "basic", meaning: "sự sạch sẽ" },
            { word: "sanitation", level: "advanced", meaning: "vệ sinh" },
            { word: "health practices", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_034",
        word: "epidemic",
        meaning: "dịch bệnh",
        pronunciation: "/ˌepɪˈdemɪk/",
        partOfSpeech: "noun",
        example: "The country faced a flu epidemic.",
        exampleTranslation: "Quốc gia đối mặt với dịch cúm.",
        synonyms: [
            { word: "outbreak", level: "intermediate", meaning: "bùng phát" },
            { word: "plague", level: "advanced", meaning: "dịch hại" },
            { word: "pandemic", level: "advanced", meaning: "đại dịch" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_035",
        word: "dosage",
        meaning: "liều lượng",
        pronunciation: "/ˈdoʊsɪdʒ/",
        partOfSpeech: "noun",
        example: "Follow the recommended dosage on the label.",
        exampleTranslation: "Tuân theo liều lượng được khuyến nghị trên nhãn.",
        synonyms: [
            { word: "dose", level: "basic", meaning: "liều" },
            { word: "amount", level: "basic", meaning: "lượng" },
            { word: "prescription", level: "intermediate", meaning: "đơn thuốc" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_036",
        word: "beneficial",
        meaning: "có lợi, có ích",
        pronunciation: "/ˌbenɪˈfɪʃl/",
        partOfSpeech: "adjective",
        example: "Omega-3 fatty acids are beneficial for heart health.",
        exampleTranslation: "Axit béo Omega-3 có lợi cho sức khỏe tim mạch.",
        synonyms: [
            { word: "helpful", level: "basic", meaning: "hữu ích" },
            { word: "advantageous", level: "advanced", meaning: "thuận lợi" },
            { word: "salutary", level: "academic", meaning: "có lợi cho sức khỏe" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_037",
        word: "detrimental",
        meaning: "có hại, bất lợi",
        pronunciation: "/ˌdetrɪˈmentl/",
        partOfSpeech: "adjective",
        example: "Smoking is detrimental to your health.",
        exampleTranslation: "Hút thuốc có hại cho sức khỏe của bạn.",
        synonyms: [
            { word: "harmful", level: "basic", meaning: "có hại" },
            { word: "damaging", level: "intermediate", meaning: "gây thiệt hại" },
            { word: "deleterious", level: "academic", meaning: "độc hại" },
        ],
        topic: "health",
        difficulty: "advanced",
    },
    {
        id: "health_038",
        word: "prescription",
        meaning: "đơn thuốc",
        pronunciation: "/prɪˈskrɪpʃn/",
        partOfSpeech: "noun",
        example: "You need a prescription to buy this medicine.",
        exampleTranslation: "Bạn cần đơn thuốc để mua loại thuốc này.",
        synonyms: [
            { word: "order", level: "basic", meaning: "yêu cầu" },
            { word: "medication order", level: "intermediate" },
            { word: "medical directive", level: "advanced" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_039",
        word: "consultation",
        meaning: "tham vấn, tư vấn",
        pronunciation: "/ˌkɒnsəlˈteɪʃn/",
        partOfSpeech: "noun",
        example: "Schedule a consultation with your doctor.",
        exampleTranslation: "Đặt lịch tư vấn với bác sĩ của bạn.",
        synonyms: [
            { word: "appointment", level: "basic", meaning: "cuộc hẹn" },
            { word: "meeting", level: "basic", meaning: "cuộc họp" },
            { word: "examination", level: "intermediate", meaning: "khám" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_040",
        word: "healthcare",
        meaning: "chăm sóc sức khỏe",
        pronunciation: "/ˈhelθker/",
        partOfSpeech: "noun",
        example: "Everyone deserves access to quality healthcare.",
        exampleTranslation: "Mọi người đều xứng đáng được tiếp cận dịch vụ chăm sóc sức khỏe chất lượng.",
        synonyms: [
            { word: "medical care", level: "basic" },
            { word: "health services", level: "intermediate" },
            { word: "medical treatment", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_041",
        word: "physical",
        meaning: "thể chất, vật lý",
        pronunciation: "/ˈfɪzɪkl/",
        partOfSpeech: "adjective",
        example: "Physical activity is essential for good health.",
        exampleTranslation: "Hoạt động thể chất là cần thiết cho sức khỏe tốt.",
        synonyms: [
            { word: "bodily", level: "intermediate", meaning: "thuộc cơ thể" },
            { word: "corporeal", level: "academic", meaning: "thuộc thể xác" },
            { word: "somatic", level: "academic", meaning: "thuộc cơ thể" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_042",
        word: "organic",
        meaning: "hữu cơ",
        pronunciation: "/ɔːrˈɡænɪk/",
        partOfSpeech: "adjective",
        example: "Organic foods are grown without pesticides.",
        exampleTranslation: "Thực phẩm hữu cơ được trồng không có thuốc trừ sâu.",
        synonyms: [
            { word: "natural", level: "basic", meaning: "tự nhiên" },
            { word: "chemical-free", level: "intermediate" },
            { word: "pesticide-free", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_043",
        word: "regulate",
        meaning: "điều chỉnh, điều hòa",
        pronunciation: "/ˈreɡjuleɪt/",
        partOfSpeech: "verb",
        example: "The body regulates temperature through sweating.",
        exampleTranslation: "Cơ thể điều hòa nhiệt độ thông qua đổ mồ hôi.",
        synonyms: [
            { word: "control", level: "basic", meaning: "kiểm soát" },
            { word: "manage", level: "intermediate", meaning: "quản lý" },
            { word: "modulate", level: "academic", meaning: "điều chỉnh" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_044",
        word: "fitness",
        meaning: "thể lực, sự cân đối",
        pronunciation: "/ˈfɪtnəs/",
        partOfSpeech: "noun",
        example: "Regular exercise improves physical fitness.",
        exampleTranslation: "Tập thể dục đều đặn cải thiện thể lực.",
        synonyms: [
            { word: "health", level: "basic", meaning: "sức khỏe" },
            { word: "condition", level: "intermediate", meaning: "tình trạng" },
            { word: "physical conditioning", level: "advanced" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_045",
        word: "calorie",
        meaning: "calo",
        pronunciation: "/ˈkæləri/",
        partOfSpeech: "noun",
        example: "Count your calories to manage weight.",
        exampleTranslation: "Đếm calo để quản lý cân nặng.",
        synonyms: [
            { word: "energy unit", level: "intermediate" },
            { word: "food energy", level: "intermediate" },
        ],
        topic: "health",
        difficulty: "beginner",
    },
    {
        id: "health_046",
        word: "cholesterol",
        meaning: "cholesterol, mỡ máu",
        pronunciation: "/kəˈlestərɒl/",
        partOfSpeech: "noun",
        example: "High cholesterol can lead to heart disease.",
        exampleTranslation: "Cholesterol cao có thể dẫn đến bệnh tim.",
        synonyms: [
            { word: "blood fat", level: "basic" },
            { word: "lipid", level: "advanced", meaning: "chất béo" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_047",
        word: "mindfulness",
        meaning: "chánh niệm, sự tỉnh thức",
        pronunciation: "/ˈmaɪndfəlnəs/",
        partOfSpeech: "noun",
        example: "Mindfulness meditation reduces stress.",
        exampleTranslation: "Thiền chánh niệm giảm căng thẳng.",
        synonyms: [
            { word: "awareness", level: "basic", meaning: "nhận thức" },
            { word: "consciousness", level: "intermediate", meaning: "ý thức" },
            { word: "attentiveness", level: "advanced", meaning: "sự chú tâm" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_048",
        word: "remedy",
        meaning: "phương thuốc, cách chữa",
        pronunciation: "/ˈremədi/",
        partOfSpeech: "noun",
        example: "Honey is a natural remedy for coughs.",
        exampleTranslation: "Mật ong là phương thuốc tự nhiên cho ho.",
        synonyms: [
            { word: "cure", level: "basic", meaning: "cách chữa" },
            { word: "treatment", level: "intermediate", meaning: "điều trị" },
            { word: "antidote", level: "advanced", meaning: "thuốc giải" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
    {
        id: "health_049",
        word: "rehabilitation",
        meaning: "phục hồi chức năng",
        pronunciation: "/ˌriːhəˌbɪlɪˈteɪʃn/",
        partOfSpeech: "noun",
        example: "He is in rehabilitation after the surgery.",
        exampleTranslation: "Anh ấy đang trong giai đoạn phục hồi chức năng sau phẫu thuật.",
        synonyms: [
            { word: "recovery", level: "basic", meaning: "hồi phục" },
            { word: "restoration", level: "advanced", meaning: "phục hồi" },
            { word: "convalescence", level: "academic", meaning: "dưỡng bệnh" },
        ],
        topic: "health",
        difficulty: "advanced",
    },
    {
        id: "health_050",
        word: "vital",
        meaning: "quan trọng, thiết yếu",
        pronunciation: "/ˈvaɪtl/",
        partOfSpeech: "adjective",
        example: "Sleep is vital for good health.",
        exampleTranslation: "Giấc ngủ rất quan trọng cho sức khỏe tốt.",
        synonyms: [
            { word: "essential", level: "basic", meaning: "thiết yếu" },
            { word: "crucial", level: "intermediate", meaning: "quan trọng" },
            { word: "indispensable", level: "advanced", meaning: "không thể thiếu" },
            { word: "imperative", level: "academic", meaning: "bắt buộc" },
        ],
        topic: "health",
        difficulty: "intermediate",
    },
];
