import { VocabularyWord } from "@/types/flashcard";

export const SOCIETY_VOCABULARY: VocabularyWord[] = [
    {
        id: "soc_001",
        word: "community",
        meaning: "cộng đồng",
        pronunciation: "/kəˈmjuːnəti/",
        partOfSpeech: "noun",
        example: "The local community organized a charity event.",
        exampleTranslation: "Cộng đồng địa phương tổ chức sự kiện từ thiện.",
        synonyms: [
            { word: "society", level: "basic", meaning: "xã hội" },
            { word: "neighborhood", level: "basic", meaning: "khu phố" },
            { word: "collective", level: "advanced", meaning: "tập thể" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_002",
        word: "equality",
        meaning: "bình đẳng",
        pronunciation: "/ɪˈkwɒləti/",
        partOfSpeech: "noun",
        example: "We must fight for equality in all areas of life.",
        exampleTranslation: "Chúng ta phải đấu tranh cho bình đẳng trong mọi lĩnh vực.",
        synonyms: [
            { word: "fairness", level: "basic", meaning: "công bằng" },
            { word: "equity", level: "advanced", meaning: "công bằng" },
            { word: "parity", level: "academic", meaning: "sự ngang bằng" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_003",
        word: "diversity",
        meaning: "sự đa dạng",
        pronunciation: "/daɪˈvɜːrsəti/",
        partOfSpeech: "noun",
        example: "Diversity makes our society stronger.",
        exampleTranslation: "Sự đa dạng làm xã hội chúng ta mạnh mẽ hơn.",
        synonyms: [
            { word: "variety", level: "basic", meaning: "đa dạng" },
            { word: "multiculturalism", level: "advanced", meaning: "đa văn hóa" },
            { word: "heterogeneity", level: "academic", meaning: "tính không đồng nhất" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_004",
        word: "discrimination",
        meaning: "phân biệt đối xử",
        pronunciation: "/dɪˌskrɪmɪˈneɪʃn/",
        partOfSpeech: "noun",
        example: "Discrimination based on race is illegal.",
        exampleTranslation: "Phân biệt đối xử dựa trên chủng tộc là bất hợp pháp.",
        synonyms: [
            { word: "prejudice", level: "intermediate", meaning: "thành kiến" },
            { word: "bias", level: "intermediate", meaning: "thiên vị" },
            { word: "inequity", level: "advanced", meaning: "bất công" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_005",
        word: "poverty",
        meaning: "nghèo đói",
        pronunciation: "/ˈpɒvərti/",
        partOfSpeech: "noun",
        example: "Poverty remains a major social issue.",
        exampleTranslation: "Nghèo đói vẫn là vấn đề xã hội lớn.",
        synonyms: [
            { word: "hardship", level: "intermediate", meaning: "khó khăn" },
            { word: "destitution", level: "advanced", meaning: "sự bần cùng" },
            { word: "indigence", level: "academic", meaning: "sự túng thiếu" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_006",
        word: "unemployment",
        meaning: "thất nghiệp",
        pronunciation: "/ˌʌnɪmˈplɔɪmənt/",
        partOfSpeech: "noun",
        example: "Unemployment rates have decreased this year.",
        exampleTranslation: "Tỷ lệ thất nghiệp đã giảm trong năm nay.",
        synonyms: [
            { word: "joblessness", level: "basic" },
            { word: "worklessness", level: "advanced" },
            { word: "redundancy", level: "advanced", meaning: "sự dư thừa" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_007",
        word: "immigration",
        meaning: "nhập cư",
        pronunciation: "/ˌɪmɪˈɡreɪʃn/",
        partOfSpeech: "noun",
        example: "Immigration policies vary between countries.",
        exampleTranslation: "Chính sách nhập cư khác nhau giữa các quốc gia.",
        synonyms: [
            { word: "migration", level: "intermediate", meaning: "di cư" },
            { word: "settlement", level: "intermediate", meaning: "định cư" },
            { word: "relocation", level: "advanced", meaning: "tái định cư" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_008",
        word: "globalization",
        meaning: "toàn cầu hóa",
        pronunciation: "/ˌɡloʊbəlaɪˈzeɪʃn/",
        partOfSpeech: "noun",
        example: "Globalization has connected cultures worldwide.",
        exampleTranslation: "Toàn cầu hóa đã kết nối các nền văn hóa trên toàn thế giới.",
        synonyms: [
            { word: "internationalization", level: "advanced" },
            { word: "global integration", level: "intermediate" },
            { word: "worldwide connection", level: "basic" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_009",
        word: "tradition",
        meaning: "truyền thống",
        pronunciation: "/trəˈdɪʃn/",
        partOfSpeech: "noun",
        example: "We should preserve our cultural traditions.",
        exampleTranslation: "Chúng ta nên bảo tồn truyền thống văn hóa.",
        synonyms: [
            { word: "custom", level: "basic", meaning: "phong tục" },
            { word: "heritage", level: "intermediate", meaning: "di sản" },
            { word: "convention", level: "advanced", meaning: "quy ước" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_010",
        word: "citizen",
        meaning: "công dân",
        pronunciation: "/ˈsɪtɪzn/",
        partOfSpeech: "noun",
        example: "Every citizen has the right to vote.",
        exampleTranslation: "Mọi công dân đều có quyền bỏ phiếu.",
        synonyms: [
            { word: "resident", level: "basic", meaning: "cư dân" },
            { word: "national", level: "intermediate", meaning: "công dân" },
            { word: "denizen", level: "academic", meaning: "cư dân" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_011",
        word: "solidarity",
        meaning: "đoàn kết",
        pronunciation: "/ˌsɒlɪˈdærəti/",
        partOfSpeech: "noun",
        example: "Solidarity among workers led to better conditions.",
        exampleTranslation: "Đoàn kết giữa công nhân dẫn đến điều kiện tốt hơn.",
        synonyms: [
            { word: "unity", level: "basic", meaning: "thống nhất" },
            { word: "togetherness", level: "intermediate", meaning: "sự gắn kết" },
            { word: "cohesion", level: "advanced", meaning: "sự gắn kết" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_012",
        word: "welfare",
        meaning: "phúc lợi",
        pronunciation: "/ˈwelfer/",
        partOfSpeech: "noun",
        example: "The government provides welfare for the poor.",
        exampleTranslation: "Chính phủ cung cấp phúc lợi cho người nghèo.",
        synonyms: [
            { word: "well-being", level: "basic", meaning: "hạnh phúc" },
            { word: "social support", level: "intermediate" },
            { word: "public assistance", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_013",
        word: "volunteer",
        meaning: "tình nguyện viên",
        pronunciation: "/ˌvɒlənˈtɪr/",
        partOfSpeech: "noun",
        example: "Volunteers helped rebuild the community.",
        exampleTranslation: "Tình nguyện viên giúp xây dựng lại cộng đồng.",
        synonyms: [
            { word: "helper", level: "basic", meaning: "người giúp đỡ" },
            { word: "contributor", level: "intermediate", meaning: "người đóng góp" },
            { word: "philanthropist", level: "advanced", meaning: "nhà từ thiện" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_014",
        word: "democracy",
        meaning: "dân chủ",
        pronunciation: "/dɪˈmɒkrəsi/",
        partOfSpeech: "noun",
        example: "Democracy gives power to the people.",
        exampleTranslation: "Dân chủ trao quyền cho người dân.",
        synonyms: [
            { word: "self-government", level: "intermediate" },
            { word: "republic", level: "intermediate", meaning: "nền cộng hòa" },
            { word: "popular sovereignty", level: "academic" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_015",
        word: "human rights",
        meaning: "nhân quyền",
        pronunciation: "/ˈhjuːmən raɪts/",
        partOfSpeech: "noun",
        example: "Human rights must be protected everywhere.",
        exampleTranslation: "Nhân quyền phải được bảo vệ ở mọi nơi.",
        synonyms: [
            { word: "civil liberties", level: "intermediate" },
            { word: "fundamental freedoms", level: "advanced" },
            { word: "basic rights", level: "basic" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_016",
        word: "stereotype",
        meaning: "định kiến, khuôn mẫu",
        pronunciation: "/ˈsteriətaɪp/",
        partOfSpeech: "noun",
        example: "We should challenge harmful stereotypes.",
        exampleTranslation: "Chúng ta nên thách thức các định kiến có hại.",
        synonyms: [
            { word: "generalization", level: "intermediate", meaning: "khái quát hóa" },
            { word: "prejudice", level: "intermediate", meaning: "thành kiến" },
            { word: "assumption", level: "intermediate", meaning: "giả định" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_017",
        word: "inequality",
        meaning: "bất bình đẳng",
        pronunciation: "/ˌɪnɪˈkwɒləti/",
        partOfSpeech: "noun",
        example: "Income inequality has increased in recent years.",
        exampleTranslation: "Bất bình đẳng thu nhập đã tăng trong những năm gần đây.",
        synonyms: [
            { word: "disparity", level: "advanced", meaning: "sự chênh lệch" },
            { word: "imbalance", level: "intermediate", meaning: "mất cân bằng" },
            { word: "inequity", level: "advanced", meaning: "bất công" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_018",
        word: "social media",
        meaning: "mạng xã hội",
        pronunciation: "/ˈsoʊʃl ˈmiːdiə/",
        partOfSpeech: "noun",
        example: "Social media influences public opinion.",
        exampleTranslation: "Mạng xã hội ảnh hưởng đến dư luận.",
        synonyms: [
            { word: "online platforms", level: "basic" },
            { word: "networking sites", level: "intermediate" },
            { word: "digital media", level: "intermediate" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_019",
        word: "urbanization",
        meaning: "đô thị hóa",
        pronunciation: "/ˌɜːrbənəˈzeɪʃn/",
        partOfSpeech: "noun",
        example: "Urbanization is transforming rural areas.",
        exampleTranslation: "Đô thị hóa đang làm thay đổi vùng nông thôn.",
        synonyms: [
            { word: "city growth", level: "basic" },
            { word: "metropolitan expansion", level: "advanced" },
            { word: "urban development", level: "intermediate" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_020",
        word: "generation gap",
        meaning: "khoảng cách thế hệ",
        pronunciation: "/ˌdʒenəˈreɪʃn ɡæp/",
        partOfSpeech: "noun",
        example: "The generation gap can cause misunderstandings.",
        exampleTranslation: "Khoảng cách thế hệ có thể gây hiểu lầm.",
        synonyms: [
            { word: "age difference", level: "basic" },
            { word: "generational divide", level: "intermediate" },
            { word: "intergenerational conflict", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_021",
        word: "tolerance",
        meaning: "khoan dung, bao dung",
        pronunciation: "/ˈtɒlərəns/",
        partOfSpeech: "noun",
        example: "Tolerance is essential for peaceful coexistence.",
        exampleTranslation: "Khoan dung là cần thiết cho sự chung sống hòa bình.",
        synonyms: [
            { word: "acceptance", level: "basic", meaning: "chấp nhận" },
            { word: "open-mindedness", level: "intermediate" },
            { word: "forbearance", level: "academic", meaning: "sự nhẫn nhịn" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_022",
        word: "integration",
        meaning: "hội nhập",
        pronunciation: "/ˌɪntɪˈɡreɪʃn/",
        partOfSpeech: "noun",
        example: "Social integration helps immigrants succeed.",
        exampleTranslation: "Hội nhập xã hội giúp người nhập cư thành công.",
        synonyms: [
            { word: "inclusion", level: "intermediate", meaning: "bao gồm" },
            { word: "assimilation", level: "advanced", meaning: "đồng hóa" },
            { word: "incorporation", level: "advanced", meaning: "hợp nhất" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_023",
        word: "activism",
        meaning: "hoạt động tích cực (đấu tranh)",
        pronunciation: "/ˈæktɪvɪzəm/",
        partOfSpeech: "noun",
        example: "Environmental activism has gained momentum.",
        exampleTranslation: "Hoạt động đấu tranh vì môi trường đã có đà phát triển.",
        synonyms: [
            { word: "advocacy", level: "intermediate", meaning: "vận động" },
            { word: "campaigning", level: "intermediate", meaning: "vận động" },
            { word: "militancy", level: "advanced", meaning: "sự đấu tranh" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_024",
        word: "culture",
        meaning: "văn hóa",
        pronunciation: "/ˈkʌltʃər/",
        partOfSpeech: "noun",
        example: "Culture shapes our values and beliefs.",
        exampleTranslation: "Văn hóa định hình giá trị và niềm tin của chúng ta.",
        synonyms: [
            { word: "civilization", level: "intermediate", meaning: "nền văn minh" },
            { word: "heritage", level: "intermediate", meaning: "di sản" },
            { word: "customs", level: "basic", meaning: "phong tục" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_025",
        word: "marginalized",
        meaning: "bị gạt ra ngoài lề",
        pronunciation: "/ˈmɑːrdʒɪnəlaɪzd/",
        partOfSpeech: "adjective",
        example: "Marginalized groups need more support.",
        exampleTranslation: "Các nhóm bị gạt ra ngoài lề cần được hỗ trợ nhiều hơn.",
        synonyms: [
            { word: "excluded", level: "intermediate", meaning: "bị loại trừ" },
            { word: "disadvantaged", level: "intermediate", meaning: "thiệt thòi" },
            { word: "disenfranchised", level: "academic", meaning: "bị tước quyền" },
        ],
        topic: "society",
        difficulty: "advanced",
    },
    {
        id: "soc_026",
        word: "homelessness",
        meaning: "tình trạng vô gia cư",
        pronunciation: "/ˈhoʊmləsnəs/",
        partOfSpeech: "noun",
        example: "Homelessness is a growing problem in cities.",
        exampleTranslation: "Vô gia cư là vấn đề ngày càng lớn ở thành phố.",
        synonyms: [
            { word: "houselessness", level: "intermediate" },
            { word: "vagrancy", level: "advanced", meaning: "sự lang thang" },
            { word: "rough sleeping", level: "intermediate" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_027",
        word: "crime",
        meaning: "tội phạm",
        pronunciation: "/kraɪm/",
        partOfSpeech: "noun",
        example: "Crime rates have decreased in recent years.",
        exampleTranslation: "Tỷ lệ tội phạm đã giảm trong những năm gần đây.",
        synonyms: [
            { word: "offense", level: "intermediate", meaning: "vi phạm" },
            { word: "wrongdoing", level: "intermediate", meaning: "hành vi sai trái" },
            { word: "felony", level: "advanced", meaning: "trọng tội" },
        ],
        topic: "society",
        difficulty: "beginner",
    },
    {
        id: "soc_028",
        word: "justice",
        meaning: "công lý",
        pronunciation: "/ˈdʒʌstɪs/",
        partOfSpeech: "noun",
        example: "Justice must be served for all.",
        exampleTranslation: "Công lý phải được thực thi cho tất cả mọi người.",
        synonyms: [
            { word: "fairness", level: "basic", meaning: "công bằng" },
            { word: "equity", level: "advanced", meaning: "công bằng" },
            { word: "righteousness", level: "advanced", meaning: "chính nghĩa" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_029",
        word: "protests",
        meaning: "biểu tình, phản đối",
        pronunciation: "/ˈproʊtests/",
        partOfSpeech: "noun",
        example: "Peaceful protests can bring about change.",
        exampleTranslation: "Biểu tình hòa bình có thể mang lại thay đổi.",
        synonyms: [
            { word: "demonstrations", level: "intermediate", meaning: "cuộc biểu tình" },
            { word: "rallies", level: "intermediate", meaning: "cuộc mít tinh" },
            { word: "uprisings", level: "advanced", meaning: "cuộc nổi dậy" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_030",
        word: "reform",
        meaning: "cải cách",
        pronunciation: "/rɪˈfɔːrm/",
        partOfSpeech: "noun",
        example: "Education reform is needed in many countries.",
        exampleTranslation: "Cải cách giáo dục cần thiết ở nhiều quốc gia.",
        synonyms: [
            { word: "change", level: "basic", meaning: "thay đổi" },
            { word: "improvement", level: "basic", meaning: "cải thiện" },
            { word: "transformation", level: "advanced", meaning: "chuyển đổi" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_031",
        word: "demographic",
        meaning: "nhân khẩu học",
        pronunciation: "/ˌdeməˈɡræfɪk/",
        partOfSpeech: "adjective",
        example: "Demographic changes affect economic growth.",
        exampleTranslation: "Thay đổi nhân khẩu học ảnh hưởng đến tăng trưởng kinh tế.",
        synonyms: [
            { word: "population-related", level: "intermediate" },
            { word: "statistical", level: "intermediate", meaning: "thống kê" },
            { word: "census-based", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_032",
        word: "aging population",
        meaning: "dân số già hóa",
        pronunciation: "/ˈeɪdʒɪŋ ˌpɒpjuˈleɪʃn/",
        partOfSpeech: "noun",
        example: "An aging population creates healthcare challenges.",
        exampleTranslation: "Dân số già hóa tạo ra thách thức về chăm sóc sức khỏe.",
        synonyms: [
            { word: "elderly population", level: "basic" },
            { word: "graying society", level: "intermediate" },
            { word: "senescent demographic", level: "academic" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_033",
        word: "social class",
        meaning: "tầng lớp xã hội",
        pronunciation: "/ˈsoʊʃl klæs/",
        partOfSpeech: "noun",
        example: "Social class affects opportunities in life.",
        exampleTranslation: "Tầng lớp xã hội ảnh hưởng đến cơ hội trong cuộc sống.",
        synonyms: [
            { word: "social status", level: "intermediate" },
            { word: "economic level", level: "intermediate" },
            { word: "stratum", level: "academic", meaning: "tầng lớp" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_034",
        word: "multiculturalism",
        meaning: "đa văn hóa",
        pronunciation: "/ˌmʌltiˈkʌltʃərəlɪzəm/",
        partOfSpeech: "noun",
        example: "Multiculturalism enriches our society.",
        exampleTranslation: "Đa văn hóa làm phong phú xã hội chúng ta.",
        synonyms: [
            { word: "cultural diversity", level: "intermediate" },
            { word: "pluralism", level: "advanced", meaning: "đa nguyên" },
            { word: "cross-cultural exchange", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_035",
        word: "gender equality",
        meaning: "bình đẳng giới",
        pronunciation: "/ˈdʒendər ɪˈkwɒləti/",
        partOfSpeech: "noun",
        example: "Gender equality is a fundamental human right.",
        exampleTranslation: "Bình đẳng giới là quyền con người cơ bản.",
        synonyms: [
            { word: "equal rights", level: "basic" },
            { word: "sexual equality", level: "intermediate" },
            { word: "gender parity", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_036",
        word: "vulnerable",
        meaning: "dễ bị tổn thương",
        pronunciation: "/ˈvʌlnərəbl/",
        partOfSpeech: "adjective",
        example: "We must protect vulnerable members of society.",
        exampleTranslation: "Chúng ta phải bảo vệ những thành viên dễ bị tổn thương trong xã hội.",
        synonyms: [
            { word: "at-risk", level: "basic" },
            { word: "susceptible", level: "advanced", meaning: "dễ bị ảnh hưởng" },
            { word: "defenseless", level: "intermediate", meaning: "không có khả năng tự vệ" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_037",
        word: "cohesion",
        meaning: "sự gắn kết",
        pronunciation: "/koʊˈhiːʒn/",
        partOfSpeech: "noun",
        example: "Social cohesion is important for stability.",
        exampleTranslation: "Sự gắn kết xã hội quan trọng cho sự ổn định.",
        synonyms: [
            { word: "unity", level: "basic", meaning: "thống nhất" },
            { word: "solidarity", level: "intermediate", meaning: "đoàn kết" },
            { word: "togetherness", level: "intermediate", meaning: "sự đoàn kết" },
        ],
        topic: "society",
        difficulty: "advanced",
    },
    {
        id: "soc_038",
        word: "harassment",
        meaning: "quấy rối",
        pronunciation: "/həˈræsmənt/",
        partOfSpeech: "noun",
        example: "Workplace harassment is unacceptable.",
        exampleTranslation: "Quấy rối nơi làm việc là không chấp nhận được.",
        synonyms: [
            { word: "bullying", level: "basic", meaning: "bắt nạt" },
            { word: "intimidation", level: "intermediate", meaning: "đe dọa" },
            { word: "persecution", level: "advanced", meaning: "bức hại" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_039",
        word: "awareness",
        meaning: "nhận thức",
        pronunciation: "/əˈwernəs/",
        partOfSpeech: "noun",
        example: "Public awareness about mental health has increased.",
        exampleTranslation: "Nhận thức công chúng về sức khỏe tâm thần đã tăng.",
        synonyms: [
            { word: "consciousness", level: "intermediate", meaning: "ý thức" },
            { word: "understanding", level: "basic", meaning: "hiểu biết" },
            { word: "cognizance", level: "academic", meaning: "sự nhận biết" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_040",
        word: "empowerment",
        meaning: "trao quyền",
        pronunciation: "/ɪmˈpaʊərmənt/",
        partOfSpeech: "noun",
        example: "Women's empowerment is key to development.",
        exampleTranslation: "Trao quyền cho phụ nữ là chìa khóa cho phát triển.",
        synonyms: [
            { word: "authorization", level: "intermediate", meaning: "ủy quyền" },
            { word: "enablement", level: "advanced" },
            { word: "capacity building", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_041",
        word: "socialization",
        meaning: "xã hội hóa",
        pronunciation: "/ˌsoʊʃəlaɪˈzeɪʃn/",
        partOfSpeech: "noun",
        example: "Socialization begins in early childhood.",
        exampleTranslation: "Xã hội hóa bắt đầu từ khi còn nhỏ.",
        synonyms: [
            { word: "social development", level: "intermediate" },
            { word: "acculturation", level: "academic", meaning: "tiếp biến văn hóa" },
            { word: "integration", level: "intermediate", meaning: "hội nhập" },
        ],
        topic: "society",
        difficulty: "advanced",
    },
    {
        id: "soc_042",
        word: "civic duty",
        meaning: "nghĩa vụ công dân",
        pronunciation: "/ˈsɪvɪk ˈdjuːti/",
        partOfSpeech: "noun",
        example: "Voting is a civic duty.",
        exampleTranslation: "Bỏ phiếu là nghĩa vụ công dân.",
        synonyms: [
            { word: "civil responsibility", level: "intermediate" },
            { word: "public obligation", level: "advanced" },
            { word: "citizenship duty", level: "intermediate" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_043",
        word: "philanthropy",
        meaning: "từ thiện",
        pronunciation: "/fɪˈlænθrəpi/",
        partOfSpeech: "noun",
        example: "Philanthropy helps address social issues.",
        exampleTranslation: "Từ thiện giúp giải quyết các vấn đề xã hội.",
        synonyms: [
            { word: "charity", level: "basic", meaning: "từ thiện" },
            { word: "generosity", level: "intermediate", meaning: "hào phóng" },
            { word: "benevolence", level: "advanced", meaning: "lòng nhân từ" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_044",
        word: "consensus",
        meaning: "sự đồng thuận",
        pronunciation: "/kənˈsensəs/",
        partOfSpeech: "noun",
        example: "We need to reach a consensus on this issue.",
        exampleTranslation: "Chúng ta cần đạt được đồng thuận về vấn đề này.",
        synonyms: [
            { word: "agreement", level: "basic", meaning: "đồng ý" },
            { word: "accord", level: "advanced", meaning: "thỏa thuận" },
            { word: "unanimity", level: "academic", meaning: "sự nhất trí" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_045",
        word: "liberty",
        meaning: "tự do",
        pronunciation: "/ˈlɪbərti/",
        partOfSpeech: "noun",
        example: "Liberty is a fundamental value in democracy.",
        exampleTranslation: "Tự do là giá trị cơ bản trong dân chủ.",
        synonyms: [
            { word: "freedom", level: "basic", meaning: "tự do" },
            { word: "independence", level: "intermediate", meaning: "độc lập" },
            { word: "autonomy", level: "advanced", meaning: "tự chủ" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_046",
        word: "controversy",
        meaning: "tranh cãi",
        pronunciation: "/ˈkɒntrəvɜːrsi/",
        partOfSpeech: "noun",
        example: "The decision sparked controversy.",
        exampleTranslation: "Quyết định gây ra tranh cãi.",
        synonyms: [
            { word: "debate", level: "basic", meaning: "tranh luận" },
            { word: "dispute", level: "intermediate", meaning: "tranh chấp" },
            { word: "contention", level: "advanced", meaning: "sự bất đồng" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_047",
        word: "social norm",
        meaning: "chuẩn mực xã hội",
        pronunciation: "/ˈsoʊʃl nɔːrm/",
        partOfSpeech: "noun",
        example: "Social norms influence our behavior.",
        exampleTranslation: "Chuẩn mực xã hội ảnh hưởng đến hành vi của chúng ta.",
        synonyms: [
            { word: "convention", level: "intermediate", meaning: "quy ước" },
            { word: "standard", level: "basic", meaning: "tiêu chuẩn" },
            { word: "custom", level: "basic", meaning: "phong tục" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_048",
        word: "civic engagement",
        meaning: "sự tham gia dân sự",
        pronunciation: "/ˈsɪvɪk ɪnˈɡeɪdʒmənt/",
        partOfSpeech: "noun",
        example: "Civic engagement strengthens democracy.",
        exampleTranslation: "Sự tham gia dân sự củng cố dân chủ.",
        synonyms: [
            { word: "public participation", level: "intermediate" },
            { word: "community involvement", level: "intermediate" },
            { word: "citizen activism", level: "advanced" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_049",
        word: "moral values",
        meaning: "giá trị đạo đức",
        pronunciation: "/ˈmɒrəl ˈvæljuːz/",
        partOfSpeech: "noun",
        example: "Moral values guide our decisions.",
        exampleTranslation: "Giá trị đạo đức hướng dẫn quyết định của chúng ta.",
        synonyms: [
            { word: "ethics", level: "intermediate", meaning: "đạo đức" },
            { word: "principles", level: "intermediate", meaning: "nguyên tắc" },
            { word: "virtues", level: "advanced", meaning: "đức hạnh" },
        ],
        topic: "society",
        difficulty: "intermediate",
    },
    {
        id: "soc_050",
        word: "populace",
        meaning: "dân chúng, quần chúng",
        pronunciation: "/ˈpɒpjələs/",
        partOfSpeech: "noun",
        example: "The populace demanded change.",
        exampleTranslation: "Dân chúng đòi hỏi thay đổi.",
        synonyms: [
            { word: "people", level: "basic", meaning: "người dân" },
            { word: "citizens", level: "basic", meaning: "công dân" },
            { word: "masses", level: "intermediate", meaning: "quần chúng" },
            { word: "public", level: "basic", meaning: "công chúng" },
        ],
        topic: "society",
        difficulty: "advanced",
    },
];
