import { VocabularyWord } from "@/types/flashcard";

export const TECHNOLOGY_VOCABULARY: VocabularyWord[] = [
    {
        id: "tech_001",
        word: "innovative",
        meaning: "sáng tạo, đổi mới",
        pronunciation: "/ˈɪnəˌveɪtɪv/",
        partOfSpeech: "adjective",
        example: "Apple is known for its innovative products.",
        exampleTranslation: "Apple nổi tiếng với các sản phẩm sáng tạo.",
        synonyms: [
            { word: "creative", level: "basic", meaning: "sáng tạo" },
            { word: "groundbreaking", level: "advanced", meaning: "đột phá" },
            { word: "cutting-edge", level: "advanced", meaning: "tiên tiến nhất" },
            { word: "pioneering", level: "academic", meaning: "tiên phong" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_002",
        word: "artificial intelligence",
        meaning: "trí tuệ nhân tạo",
        pronunciation: "/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/",
        partOfSpeech: "noun",
        example: "Artificial intelligence is transforming many industries.",
        exampleTranslation: "Trí tuệ nhân tạo đang thay đổi nhiều ngành công nghiệp.",
        synonyms: [
            { word: "AI", level: "basic", meaning: "AI" },
            { word: "machine intelligence", level: "intermediate" },
            { word: "cognitive computing", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_003",
        word: "data",
        meaning: "dữ liệu, thông tin",
        pronunciation: "/ˈdeɪtə/",
        partOfSpeech: "noun",
        example: "Big data helps companies make better decisions.",
        exampleTranslation: "Dữ liệu lớn giúp các công ty đưa ra quyết định tốt hơn.",
        synonyms: [
            { word: "information", level: "basic", meaning: "thông tin" },
            { word: "statistics", level: "intermediate", meaning: "số liệu thống kê" },
            { word: "metrics", level: "advanced", meaning: "các chỉ số" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_004",
        word: "algorithm",
        meaning: "thuật toán",
        pronunciation: "/ˈælɡərɪðəm/",
        partOfSpeech: "noun",
        example: "Social media algorithms determine what content you see.",
        exampleTranslation: "Thuật toán mạng xã hội quyết định nội dung bạn thấy.",
        synonyms: [
            { word: "formula", level: "basic", meaning: "công thức" },
            { word: "procedure", level: "intermediate", meaning: "quy trình" },
            { word: "computational method", level: "academic" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_005",
        word: "automate",
        meaning: "tự động hóa",
        pronunciation: "/ˈɔːtəmeɪt/",
        partOfSpeech: "verb",
        example: "Companies automate repetitive tasks to save time.",
        exampleTranslation: "Các công ty tự động hóa các tác vụ lặp lại để tiết kiệm thời gian.",
        synonyms: [
            { word: "mechanize", level: "intermediate", meaning: "cơ giới hóa" },
            { word: "streamline", level: "advanced", meaning: "hợp lý hóa" },
            { word: "systematize", level: "academic", meaning: "hệ thống hóa" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_006",
        word: "cybersecurity",
        meaning: "an ninh mạng",
        pronunciation: "/ˌsaɪbərsiˈkjʊrəti/",
        partOfSpeech: "noun",
        example: "Cybersecurity is essential for protecting personal data.",
        exampleTranslation: "An ninh mạng rất cần thiết để bảo vệ dữ liệu cá nhân.",
        synonyms: [
            { word: "online security", level: "basic" },
            { word: "information security", level: "intermediate" },
            { word: "digital protection", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_007",
        word: "cloud computing",
        meaning: "điện toán đám mây",
        pronunciation: "/klaʊd kəmˈpjuːtɪŋ/",
        partOfSpeech: "noun",
        example: "Cloud computing allows access to data from anywhere.",
        exampleTranslation: "Điện toán đám mây cho phép truy cập dữ liệu từ bất kỳ đâu.",
        synonyms: [
            { word: "cloud services", level: "basic" },
            { word: "remote computing", level: "intermediate" },
            { word: "distributed computing", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_008",
        word: "software",
        meaning: "phần mềm",
        pronunciation: "/ˈsɒftwer/",
        partOfSpeech: "noun",
        example: "This software helps manage customer relationships.",
        exampleTranslation: "Phần mềm này giúp quản lý quan hệ khách hàng.",
        synonyms: [
            { word: "program", level: "basic", meaning: "chương trình" },
            { word: "application", level: "basic", meaning: "ứng dụng" },
            { word: "platform", level: "intermediate", meaning: "nền tảng" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_009",
        word: "hardware",
        meaning: "phần cứng",
        pronunciation: "/ˈhɑːrdwer/",
        partOfSpeech: "noun",
        example: "The company manufactures computer hardware.",
        exampleTranslation: "Công ty sản xuất phần cứng máy tính.",
        synonyms: [
            { word: "equipment", level: "basic", meaning: "thiết bị" },
            { word: "machinery", level: "intermediate", meaning: "máy móc" },
            { word: "apparatus", level: "advanced", meaning: "bộ máy" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_010",
        word: "digital",
        meaning: "kỹ thuật số, số hóa",
        pronunciation: "/ˈdɪdʒɪtl/",
        partOfSpeech: "adjective",
        example: "The digital revolution has changed how we communicate.",
        exampleTranslation: "Cuộc cách mạng số đã thay đổi cách chúng ta giao tiếp.",
        synonyms: [
            { word: "electronic", level: "basic", meaning: "điện tử" },
            { word: "computerized", level: "intermediate", meaning: "vi tính hóa" },
            { word: "virtual", level: "intermediate", meaning: "ảo" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_011",
        word: "upgrade",
        meaning: "nâng cấp",
        pronunciation: "/ˈʌpɡreɪd/",
        partOfSpeech: "verb",
        example: "You should upgrade your operating system regularly.",
        exampleTranslation: "Bạn nên nâng cấp hệ điều hành thường xuyên.",
        synonyms: [
            { word: "improve", level: "basic", meaning: "cải thiện" },
            { word: "enhance", level: "intermediate", meaning: "nâng cao" },
            { word: "optimize", level: "advanced", meaning: "tối ưu hóa" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_012",
        word: "download",
        meaning: "tải xuống",
        pronunciation: "/ˈdaʊnloʊd/",
        partOfSpeech: "verb",
        example: "You can download the app for free.",
        exampleTranslation: "Bạn có thể tải xuống ứng dụng miễn phí.",
        synonyms: [
            { word: "install", level: "basic", meaning: "cài đặt" },
            { word: "retrieve", level: "advanced", meaning: "truy xuất" },
            { word: "fetch", level: "intermediate", meaning: "lấy về" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_013",
        word: "blockchain",
        meaning: "chuỗi khối",
        pronunciation: "/ˈblɒktʃeɪn/",
        partOfSpeech: "noun",
        example: "Blockchain technology powers cryptocurrencies like Bitcoin.",
        exampleTranslation: "Công nghệ blockchain hỗ trợ các loại tiền mã hóa như Bitcoin.",
        synonyms: [
            { word: "distributed ledger", level: "advanced" },
            { word: "decentralized database", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "advanced",
    },
    {
        id: "tech_014",
        word: "startup",
        meaning: "công ty khởi nghiệp",
        pronunciation: "/ˈstɑːrtʌp/",
        partOfSpeech: "noun",
        example: "Many tech startups are based in Silicon Valley.",
        exampleTranslation: "Nhiều công ty khởi nghiệp công nghệ đặt trụ sở tại Thung lũng Silicon.",
        synonyms: [
            { word: "new business", level: "basic" },
            { word: "venture", level: "intermediate", meaning: "dự án kinh doanh" },
            { word: "enterprise", level: "advanced", meaning: "doanh nghiệp" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_015",
        word: "virtual reality",
        meaning: "thực tế ảo",
        pronunciation: "/ˈvɜːrtʃuəl riˈæləti/",
        partOfSpeech: "noun",
        example: "Virtual reality is used for gaming and training.",
        exampleTranslation: "Thực tế ảo được sử dụng cho trò chơi và đào tạo.",
        synonyms: [
            { word: "VR", level: "basic" },
            { word: "immersive technology", level: "advanced" },
            { word: "simulated environment", level: "academic" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_016",
        word: "efficient",
        meaning: "hiệu quả",
        pronunciation: "/ɪˈfɪʃnt/",
        partOfSpeech: "adjective",
        example: "The new system is more efficient than the old one.",
        exampleTranslation: "Hệ thống mới hiệu quả hơn hệ thống cũ.",
        synonyms: [
            { word: "effective", level: "basic", meaning: "có hiệu lực" },
            { word: "productive", level: "intermediate", meaning: "năng suất" },
            { word: "streamlined", level: "advanced", meaning: "tinh gọn" },
            { word: "optimized", level: "advanced", meaning: "tối ưu" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_017",
        word: "bandwidth",
        meaning: "băng thông",
        pronunciation: "/ˈbændwɪdθ/",
        partOfSpeech: "noun",
        example: "Video streaming requires high bandwidth.",
        exampleTranslation: "Phát video trực tuyến yêu cầu băng thông cao.",
        synonyms: [
            { word: "capacity", level: "basic", meaning: "dung lượng" },
            { word: "data rate", level: "intermediate" },
            { word: "throughput", level: "advanced", meaning: "thông lượng" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_018",
        word: "interface",
        meaning: "giao diện",
        pronunciation: "/ˈɪntərfeɪs/",
        partOfSpeech: "noun",
        example: "The user interface is simple and intuitive.",
        exampleTranslation: "Giao diện người dùng đơn giản và trực quan.",
        synonyms: [
            { word: "UI", level: "basic" },
            { word: "dashboard", level: "intermediate", meaning: "bảng điều khiển" },
            { word: "control panel", level: "intermediate" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_019",
        word: "encrypt",
        meaning: "mã hóa",
        pronunciation: "/ɪnˈkrɪpt/",
        partOfSpeech: "verb",
        example: "It's important to encrypt sensitive data.",
        exampleTranslation: "Điều quan trọng là phải mã hóa dữ liệu nhạy cảm.",
        synonyms: [
            { word: "code", level: "basic", meaning: "mã" },
            { word: "encode", level: "intermediate", meaning: "mã hóa" },
            { word: "cipher", level: "advanced", meaning: "mật mã hóa" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_020",
        word: "database",
        meaning: "cơ sở dữ liệu",
        pronunciation: "/ˈdeɪtəbeɪs/",
        partOfSpeech: "noun",
        example: "All customer information is stored in a database.",
        exampleTranslation: "Tất cả thông tin khách hàng được lưu trữ trong cơ sở dữ liệu.",
        synonyms: [
            { word: "data storage", level: "basic" },
            { word: "repository", level: "advanced", meaning: "kho lưu trữ" },
            { word: "data warehouse", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_021",
        word: "machine learning",
        meaning: "học máy",
        pronunciation: "/məˈʃiːn ˈlɜːrnɪŋ/",
        partOfSpeech: "noun",
        example: "Machine learning enables computers to learn from data.",
        exampleTranslation: "Học máy cho phép máy tính học từ dữ liệu.",
        synonyms: [
            { word: "ML", level: "basic" },
            { word: "predictive modeling", level: "advanced" },
            { word: "deep learning", level: "advanced", meaning: "học sâu" },
        ],
        topic: "technology",
        difficulty: "advanced",
    },
    {
        id: "tech_022",
        word: "network",
        meaning: "mạng, hệ thống mạng",
        pronunciation: "/ˈnetwɜːrk/",
        partOfSpeech: "noun",
        example: "The company has a secure network infrastructure.",
        exampleTranslation: "Công ty có cơ sở hạ tầng mạng an toàn.",
        synonyms: [
            { word: "system", level: "basic", meaning: "hệ thống" },
            { word: "infrastructure", level: "advanced", meaning: "cơ sở hạ tầng" },
            { word: "grid", level: "intermediate", meaning: "lưới" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_023",
        word: "server",
        meaning: "máy chủ",
        pronunciation: "/ˈsɜːrvər/",
        partOfSpeech: "noun",
        example: "The website is hosted on a cloud server.",
        exampleTranslation: "Trang web được lưu trữ trên máy chủ đám mây.",
        synonyms: [
            { word: "host", level: "basic" },
            { word: "mainframe", level: "advanced" },
            { word: "node", level: "intermediate", meaning: "nút mạng" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_024",
        word: "responsive",
        meaning: "đáp ứng, tương thích",
        pronunciation: "/rɪˈspɒnsɪv/",
        partOfSpeech: "adjective",
        example: "The website has a responsive design for mobile devices.",
        exampleTranslation: "Trang web có thiết kế đáp ứng cho thiết bị di động.",
        synonyms: [
            { word: "adaptive", level: "intermediate", meaning: "thích ứng" },
            { word: "flexible", level: "basic", meaning: "linh hoạt" },
            { word: "dynamic", level: "intermediate", meaning: "năng động" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_025",
        word: "scalable",
        meaning: "có khả năng mở rộng",
        pronunciation: "/ˈskeɪləbl/",
        partOfSpeech: "adjective",
        example: "We need a scalable solution for growing traffic.",
        exampleTranslation: "Chúng tôi cần giải pháp có khả năng mở rộng cho lưu lượng truy cập tăng.",
        synonyms: [
            { word: "expandable", level: "basic", meaning: "có thể mở rộng" },
            { word: "extensible", level: "advanced", meaning: "có thể mở rộng" },
            { word: "modular", level: "advanced", meaning: "theo mô-đun" },
        ],
        topic: "technology",
        difficulty: "advanced",
    },
    {
        id: "tech_026",
        word: "integrate",
        meaning: "tích hợp",
        pronunciation: "/ˈɪntɪɡreɪt/",
        partOfSpeech: "verb",
        example: "We can integrate this tool with existing systems.",
        exampleTranslation: "Chúng tôi có thể tích hợp công cụ này với các hệ thống hiện có.",
        synonyms: [
            { word: "combine", level: "basic", meaning: "kết hợp" },
            { word: "merge", level: "intermediate", meaning: "hợp nhất" },
            { word: "incorporate", level: "advanced", meaning: "hợp nhất" },
            { word: "unify", level: "advanced", meaning: "thống nhất" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_027",
        word: "analyze",
        meaning: "phân tích",
        pronunciation: "/ˈænəlaɪz/",
        partOfSpeech: "verb",
        example: "We analyze user behavior to improve the product.",
        exampleTranslation: "Chúng tôi phân tích hành vi người dùng để cải thiện sản phẩm.",
        synonyms: [
            { word: "examine", level: "basic", meaning: "kiểm tra" },
            { word: "assess", level: "intermediate", meaning: "đánh giá" },
            { word: "evaluate", level: "intermediate", meaning: "đánh giá" },
            { word: "scrutinize", level: "academic", meaning: "xem xét kỹ" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_028",
        word: "debug",
        meaning: "gỡ lỗi",
        pronunciation: "/diːˈbʌɡ/",
        partOfSpeech: "verb",
        example: "Developers spend hours debugging code.",
        exampleTranslation: "Các nhà phát triển dành hàng giờ để gỡ lỗi mã.",
        synonyms: [
            { word: "fix", level: "basic", meaning: "sửa" },
            { word: "troubleshoot", level: "intermediate", meaning: "khắc phục sự cố" },
            { word: "resolve issues", level: "intermediate" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_029",
        word: "deploy",
        meaning: "triển khai",
        pronunciation: "/dɪˈplɔɪ/",
        partOfSpeech: "verb",
        example: "We will deploy the new feature next week.",
        exampleTranslation: "Chúng tôi sẽ triển khai tính năng mới vào tuần tới.",
        synonyms: [
            { word: "launch", level: "basic", meaning: "ra mắt" },
            { word: "implement", level: "intermediate", meaning: "thực hiện" },
            { word: "roll out", level: "intermediate", meaning: "triển khai" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_030",
        word: "obsolete",
        meaning: "lỗi thời, không còn sử dụng",
        pronunciation: "/ˌɒbsəˈliːt/",
        partOfSpeech: "adjective",
        example: "This technology has become obsolete.",
        exampleTranslation: "Công nghệ này đã trở nên lỗi thời.",
        synonyms: [
            { word: "outdated", level: "basic", meaning: "lỗi thời" },
            { word: "antiquated", level: "advanced", meaning: "cổ hủ" },
            { word: "deprecated", level: "advanced", meaning: "không còn hỗ trợ" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_031",
        word: "synchronize",
        meaning: "đồng bộ hóa",
        pronunciation: "/ˈsɪŋkrənaɪz/",
        partOfSpeech: "verb",
        example: "The app synchronizes data across all devices.",
        exampleTranslation: "Ứng dụng đồng bộ hóa dữ liệu trên tất cả thiết bị.",
        synonyms: [
            { word: "sync", level: "basic" },
            { word: "coordinate", level: "intermediate", meaning: "phối hợp" },
            { word: "harmonize", level: "advanced", meaning: "hài hòa" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_032",
        word: "wireless",
        meaning: "không dây",
        pronunciation: "/ˈwaɪərləs/",
        partOfSpeech: "adjective",
        example: "Wireless charging is becoming more common.",
        exampleTranslation: "Sạc không dây đang trở nên phổ biến hơn.",
        synonyms: [
            { word: "cordless", level: "basic", meaning: "không dây" },
            { word: "Wi-Fi enabled", level: "intermediate" },
            { word: "untethered", level: "advanced", meaning: "không bị ràng buộc" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_033",
        word: "compatible",
        meaning: "tương thích",
        pronunciation: "/kəmˈpætəbl/",
        partOfSpeech: "adjective",
        example: "This software is compatible with Windows and Mac.",
        exampleTranslation: "Phần mềm này tương thích với Windows và Mac.",
        synonyms: [
            { word: "suitable", level: "basic", meaning: "phù hợp" },
            { word: "harmonious", level: "advanced", meaning: "hài hòa" },
            { word: "interoperable", level: "academic", meaning: "có thể tương tác" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_034",
        word: "backup",
        meaning: "sao lưu",
        pronunciation: "/ˈbækʌp/",
        partOfSpeech: "noun",
        example: "Always create a backup of important files.",
        exampleTranslation: "Luôn tạo bản sao lưu các tệp quan trọng.",
        synonyms: [
            { word: "copy", level: "basic", meaning: "bản sao" },
            { word: "duplicate", level: "intermediate", meaning: "bản trùng lặp" },
            { word: "archive", level: "advanced", meaning: "lưu trữ" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_035",
        word: "prototype",
        meaning: "nguyên mẫu",
        pronunciation: "/ˈproʊtətaɪp/",
        partOfSpeech: "noun",
        example: "We built a prototype to test the concept.",
        exampleTranslation: "Chúng tôi xây dựng một nguyên mẫu để thử nghiệm ý tưởng.",
        synonyms: [
            { word: "model", level: "basic", meaning: "mô hình" },
            { word: "sample", level: "basic", meaning: "mẫu" },
            { word: "mock-up", level: "intermediate", meaning: "mô hình thử" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_036",
        word: "user-friendly",
        meaning: "thân thiện với người dùng",
        pronunciation: "/ˈjuːzər ˈfrendli/",
        partOfSpeech: "adjective",
        example: "The app has a user-friendly interface.",
        exampleTranslation: "Ứng dụng có giao diện thân thiện với người dùng.",
        synonyms: [
            { word: "easy to use", level: "basic" },
            { word: "intuitive", level: "intermediate", meaning: "trực quan" },
            { word: "accessible", level: "intermediate", meaning: "dễ tiếp cận" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_037",
        word: "bug",
        meaning: "lỗi (phần mềm)",
        pronunciation: "/bʌɡ/",
        partOfSpeech: "noun",
        example: "The developers fixed several bugs in the latest update.",
        exampleTranslation: "Các nhà phát triển đã sửa nhiều lỗi trong bản cập nhật mới nhất.",
        synonyms: [
            { word: "error", level: "basic", meaning: "lỗi" },
            { word: "glitch", level: "intermediate", meaning: "trục trặc" },
            { word: "defect", level: "advanced", meaning: "khuyết điểm" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_038",
        word: "connectivity",
        meaning: "khả năng kết nối",
        pronunciation: "/ˌkɒnekˈtɪvəti/",
        partOfSpeech: "noun",
        example: "Good connectivity is essential for remote work.",
        exampleTranslation: "Khả năng kết nối tốt là cần thiết cho làm việc từ xa.",
        synonyms: [
            { word: "connection", level: "basic", meaning: "kết nối" },
            { word: "network access", level: "intermediate" },
            { word: "interoperability", level: "academic" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_039",
        word: "cache",
        meaning: "bộ nhớ đệm",
        pronunciation: "/kæʃ/",
        partOfSpeech: "noun",
        example: "Clear your browser cache to fix loading issues.",
        exampleTranslation: "Xóa bộ nhớ đệm trình duyệt để khắc phục sự cố tải trang.",
        synonyms: [
            { word: "temporary storage", level: "intermediate" },
            { word: "buffer", level: "advanced", meaning: "bộ đệm" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_040",
        word: "cutting-edge",
        meaning: "tiên tiến nhất, hiện đại nhất",
        pronunciation: "/ˈkʌtɪŋ edʒ/",
        partOfSpeech: "adjective",
        example: "This research uses cutting-edge technology.",
        exampleTranslation: "Nghiên cứu này sử dụng công nghệ tiên tiến nhất.",
        synonyms: [
            { word: "advanced", level: "basic", meaning: "tiên tiến" },
            { word: "state-of-the-art", level: "advanced", meaning: "hiện đại nhất" },
            { word: "pioneering", level: "academic", meaning: "tiên phong" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_041",
        word: "automation",
        meaning: "sự tự động hóa",
        pronunciation: "/ˌɔːtəˈmeɪʃn/",
        partOfSpeech: "noun",
        example: "Automation has transformed manufacturing industries.",
        exampleTranslation: "Tự động hóa đã thay đổi các ngành công nghiệp sản xuất.",
        synonyms: [
            { word: "mechanization", level: "intermediate", meaning: "cơ giới hóa" },
            { word: "robotization", level: "advanced" },
            { word: "computerization", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_042",
        word: "Internet of Things",
        meaning: "Internet vạn vật",
        pronunciation: "/ˈɪntərnet əv θɪŋz/",
        partOfSpeech: "noun",
        example: "The Internet of Things connects everyday devices.",
        exampleTranslation: "Internet vạn vật kết nối các thiết bị hàng ngày.",
        synonyms: [
            { word: "IoT", level: "basic" },
            { word: "connected devices", level: "intermediate" },
            { word: "smart technology", level: "intermediate" },
        ],
        topic: "technology",
        difficulty: "advanced",
    },
    {
        id: "tech_043",
        word: "privacy",
        meaning: "quyền riêng tư",
        pronunciation: "/ˈprɪvəsi/",
        partOfSpeech: "noun",
        example: "Online privacy is a growing concern.",
        exampleTranslation: "Quyền riêng tư trực tuyến là mối lo ngại ngày càng tăng.",
        synonyms: [
            { word: "confidentiality", level: "advanced", meaning: "tính bảo mật" },
            { word: "secrecy", level: "intermediate", meaning: "bí mật" },
            { word: "anonymity", level: "advanced", meaning: "ẩn danh" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_044",
        word: "hacker",
        meaning: "tin tặc",
        pronunciation: "/ˈhækər/",
        partOfSpeech: "noun",
        example: "Hackers stole millions of user accounts.",
        exampleTranslation: "Tin tặc đã đánh cắp hàng triệu tài khoản người dùng.",
        synonyms: [
            { word: "cyber criminal", level: "intermediate" },
            { word: "intruder", level: "intermediate", meaning: "kẻ xâm nhập" },
            { word: "attacker", level: "intermediate", meaning: "kẻ tấn công" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_045",
        word: "bandwidth",
        meaning: "băng thông",
        pronunciation: "/ˈbændwɪdθ/",
        partOfSpeech: "noun",
        example: "Streaming videos requires high bandwidth.",
        exampleTranslation: "Phát video trực tuyến yêu cầu băng thông cao.",
        synonyms: [
            { word: "capacity", level: "basic", meaning: "dung lượng" },
            { word: "throughput", level: "advanced", meaning: "thông lượng" },
            { word: "data transfer rate", level: "intermediate" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_046",
        word: "navigate",
        meaning: "điều hướng, tìm đường",
        pronunciation: "/ˈnævɪɡeɪt/",
        partOfSpeech: "verb",
        example: "The app helps users navigate through the city.",
        exampleTranslation: "Ứng dụng giúp người dùng điều hướng qua thành phố.",
        synonyms: [
            { word: "browse", level: "basic", meaning: "duyệt" },
            { word: "explore", level: "basic", meaning: "khám phá" },
            { word: "traverse", level: "advanced", meaning: "đi qua" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_047",
        word: "malware",
        meaning: "phần mềm độc hại",
        pronunciation: "/ˈmælwer/",
        partOfSpeech: "noun",
        example: "Antivirus software protects against malware.",
        exampleTranslation: "Phần mềm diệt virus bảo vệ chống lại phần mềm độc hại.",
        synonyms: [
            { word: "virus", level: "basic" },
            { word: "malicious software", level: "intermediate" },
            { word: "spyware", level: "intermediate" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_048",
        word: "streaming",
        meaning: "truyền phát trực tuyến",
        pronunciation: "/ˈstriːmɪŋ/",
        partOfSpeech: "noun",
        example: "Video streaming has become very popular.",
        exampleTranslation: "Truyền phát video trực tuyến đã trở nên rất phổ biến.",
        synonyms: [
            { word: "broadcasting", level: "intermediate", meaning: "phát sóng" },
            { word: "live transmission", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "beginner",
    },
    {
        id: "tech_049",
        word: "open-source",
        meaning: "mã nguồn mở",
        pronunciation: "/ˈoʊpən sɔːrs/",
        partOfSpeech: "adjective",
        example: "Many developers prefer open-source software.",
        exampleTranslation: "Nhiều nhà phát triển thích phần mềm mã nguồn mở.",
        synonyms: [
            { word: "free software", level: "basic" },
            { word: "public domain", level: "intermediate" },
            { word: "community-driven", level: "advanced" },
        ],
        topic: "technology",
        difficulty: "intermediate",
    },
    {
        id: "tech_050",
        word: "API",
        meaning: "giao diện lập trình ứng dụng",
        pronunciation: "/ˌeɪ piː ˈaɪ/",
        partOfSpeech: "noun",
        example: "Developers use APIs to connect different services.",
        exampleTranslation: "Các nhà phát triển sử dụng API để kết nối các dịch vụ khác nhau.",
        synonyms: [
            { word: "interface", level: "basic", meaning: "giao diện" },
            { word: "web service", level: "intermediate" },
            { word: "endpoint", level: "advanced", meaning: "điểm cuối" },
        ],
        topic: "technology",
        difficulty: "advanced",
    },
];
